### ISSUE TITLE
SEO ошибки

### ISSUE THREAD

**Issue by MityaDementiy** [Hexlet/hexlet-sicp#107]
Ребята, результаты SEO-аудита сайта:

- [ ] дублирующиеся тайтлы, серьёзная ошибка https://drive.google.com/open?id=17sjSeIWcN22XrCcZrGM7FzMu4IQVrhHa 

- [ ] — дублирующийся контент, серьёзная ошибка https://drive.google.com/open?id=1BrVov8OYVIpymTVsIt6ftPQ8aQxkTvXV

- [x] — нет карты sitemap.xml, должна быть по URL https://sicp.hexlet.io/sitemap.xml, серьёзная ошибка

- [ ] — смешанный контент, ссылки на http, ошибка https://drive.google.com/open?id=1BrVov8OYVIpymTVsIt6ftPQ8aQxkTvXV 

- [ ] — проблемы с метаописанием, ошибка https://drive.google.com/open?id=1XtnkTugE2P1jkJnUDTAiS8J62NxwhCrU 

- [ ] — uncompressed pages (некэшированные, насколько понимаю), ошибка https://drive.google.com/open?id=1GLNy4-hVEjh8Ptn7qEp87UmlvblCD60U 

- [ ] — мало текста на странице, ошибка https://drive.google.com/open?id=1GLNy4-hVEjh8Ptn7qEp87UmlvblCD60U 

- [ ] — низкое соотношение текста к HTML, ошибка https://drive.google.com/open?id=1noL8ESNMxmOudWFU5Aan0P2_tp5PwjC1

- [ ] — на страницах нет заголовка h1, ошибка https://drive.google.com/open?id=1noL8ESNMxmOudWFU5Aan0P2_tp5PwjC1 

- [ ] — временные редиректы, нужны постоянные, ошибка https://drive.google.com/open?id=17D2kEZr4AMFR57wFFd8v5eMEoQNiQ58b 

- [ ] — дублирующиеся h1 и title, ошибка.

**Comment by badta5te** [comment]
Хочу попробовать свои силы, возьму первый таск.
В случае если находимся на вкладке, то в качестве заголовка имя вкладки?
В случае нахождения на странице главы, имя главы?
Или 'Hexlet SICP: заголовок'?

**Comment by fey** [comment]
Давай как на хекслете `без hexlet SICP` название страницы в зависимости от контекста.

**Comment by fey** [comment]
@MityaDementiy на страницах глав https://sicp.hexlet.io/chapters/1 к примеру есть h1 теги
```
<h1 class="h2">1. Построение абстракций с помощью процедур</h1>
```
Проблема в классах или в чем?

**Comment by MityaDementiy** [comment]
Робот SEMRush их почему-то не видит, значит могут не видеть и роботы поисковиков.

**Comment by zhabinka** [comment]
Предлагаю отметить в списке уже реализованные задачи.

**Comment by zhabinka** [comment]
@badta5te получилось разобраться с тайтлами?

**Comment by badta5te** [comment]
@zhabinka почти, на выходных, скорее всего, добью задачу, надо изучить как правильно это сделать

**Comment by zhabinka** [comment]
@badta5te, как дела? :)

**Comment by ashikov** [comment]
Ребят, тут доки с ошибками уже недоступны. @fey, я так понимаю нужен повторный SEO-аудит. Мы это сейчас можем сделать?

**Comment by fey** [comment]
Угу, попроси Сашу

**Comment by ashikov** [comment]
Дело сделано 🙂

**Comment by acidmaksim** [comment]
@ashikov дело сделано значит закрываем задачу? Или ты только спросил пока ?

**Comment by ashikov** [comment]
Попросил Сашу

**Comment by ashikov** [comment]
Саша расписал, что нужно сделать. 
[правки sicp.hexlet.io.docx](https://github.com/Hexlet/hexlet-sicp/files/9947989/sicp.hexlet.io.docx)
Предлагаю разбить этот issue на более мелкие задачи. Записал себе, чуть позже займусь, если вы меня не остановите, конечно. :)

**Comment by ashikov** [comment]
Для удобства контрибьюторов закрою этот issue и сделаю новый, с актуальным списком задач.
