### ISSUE TITLE
Не работает сброс пароля для залогиненного пользователя

### ISSUE THREAD

**Issue by fey** [Hexlet/hexlet-sicp#1090]

**Comment by ashikov** [comment]
@fey попробую пофиксить

**Comment by ashikov** [comment]
@fey Слушай, а ишью не должен автоматом закрываться если есть смерженный PR в котором он меншится? Нужно вручную это делать? Где-то помню уже был такой вопрос, вот только ответ на него я забыл.

**Comment by fey** [comment]
@ashikov нужно в ПР написать типа `closes #123`
