### ISSUE TITLE
SEO: Закрыть кодревью

### ISSUE THREAD

**Issue by fey** [Hexlet/hexlet-sicp#1208]
Нужно закрыть от индексации страницы кодревью. В head страниц нужно добавить тег **<meta name="robots" content="noindex, nofollow"/>.** 

примеры страниц: 
https://sicp.hexlet.io/solutions/683
https://sicp.hexlet.io/solutions/59
https://sicp.hexlet.io/solutions/53
https://sicp.hexlet.io/ru/solutions/718

**Comment by nastasja83** [comment]
взяла в работу
