### ISSUE TITLE
Добавить упражнения

### ISSUE THREAD

**Issue by zhabinka** [Hexlet/hexlet-sicp#122]
- [x] Добавить миграцию
- [x] Добавить seed
- [x] Вывести список упражнений на странице
- [x] Вывести упражнения в основном списке с главами
- [x] Добавить возможность отмечать пройденные упражнения
- [ ] Добавить описание упражнений

**Comment by zhabinka** [comment]
https://github.com/Hexlet/hexlet-sicp/pull/132

**Comment by fey** [comment]
Я его смержил, можно другой ПР сделать, а прогресс тут отмечать. @zhabinka
