### ISSUE TITLE
Не сохраняется фильтрация при переходе на следующую страницу списка решений

### ISSUE THREAD

**Issue by burenkov-anton** [Hexlet/hexlet-sicp#1257]
На [странице с фильтрами](https://sicp.hexlet.io/ru/solutions?filter%5Buser_id%5D=&filter%5Bexercise_id%5D=3) 
при нажатии на 2ую страницу открывается [страница без фильтров](https://sicp.hexlet.io/ru/solutions?page=2)

**Comment by fey** [comment]
fixed
