### ISSUE TITLE
Bootstrap 4 && Bootsrap 5 refactoring / app.blade.php

### ISSUE THREAD

**Issue by rddeveloper2019** [Hexlet/hexlet-sicp#1275]
Bootstrap 4 && Bootsrap 5 layout and classes refactoring in app.blade.php file

**Comment by fey** [comment]
Часть комментов здесь - https://github.com/Hexlet/hexlet-sicp/pull/1274

**Comment by rddeveloper2019** [comment]
Вроде исправил.
