### ISSUE TITLE
Поправить верстку кнопки закрытия модального окна

### ISSUE THREAD

**Issue by amshkv** [Hexlet/hexlet-sicp#1306]
<img width="541" alt="image" src="https://user-images.githubusercontent.com/23584933/169287747-0fc7f6a4-ee3c-429a-b383-7a11c1a5d40f.png">
https://sicp.hexlet.io/ru/chapters/5
при клике показать кто завершил в модалке кнопка без стилей
возможно еще где-то попадется

**Comment by frwellmonalisa** [comment]
@amshkv А в каком браузере возникает этот баг?
Можешь повесить лейбл `frontend` на этот issue?

**Comment by amshkv** [comment]
кажется что это просто стили кнопки не обновили при переезде на бутстрап 5 :)

**Comment by funkylen** [comment]
Забрал

**Comment by funkylen** [comment]
#1316
