### ISSUE TITLE
Сделать редирект с https://hexlet-sicp.herokuapp.com на sicp.hexlet.io

### ISSUE THREAD

**Issue by grozwalker** [Hexlet/hexlet-sicp#1309]
Сделать редирект с https://hexlet-sicp.herokuapp.com на sicp.hexlet.io потому что для сео это плохо

**Comment by fey** [comment]
код ответа 301?

**Comment by fey** [comment]
done

**Comment by fey** [comment]
https://github.com/Hexlet/hexlet-sicp/pull/1313
