### ISSUE TITLE
добавить вкладку с решением в редактор

### ISSUE THREAD

**Issue by fey** [Hexlet/hexlet-sicp#1312]

**Comment by ashikov** [comment]
@acidmaksim это тоже сделано, насколько я понимаю.
<img width="671" alt="Screenshot 2022-09-03 at 20 58 12" src="https://user-images.githubusercontent.com/676554/188273761-d33477ce-0534-448b-870a-1392e13310d2.png">

**Comment by acidmaksim** [comment]
@ashikov видимо, но лучше спросить у  @fey 
Он ставил задачу, меня еще не было)

**Comment by ashikov** [comment]
@fey скажи что-нибудь, плиз 😅

**Comment by fey** [comment]
Да, можно закрыть. Давай добавим ишшус, чтобы сделать таймер как на код бейзиксе, чтобы не сразу показывать решение

**Comment by ashikov** [comment]
Ага. Будет круто. Добавил Issue: https://github.com/Hexlet/hexlet-sicp/issues/1348
