### ISSUE TITLE
Окно с выводами вылазит на footer при большой высоте.

### ISSUE THREAD

**Issue by MAGLeb** [Hexlet/hexlet-sicp#1320]
В первую очередь выражаю большую благодарность за существующую платформу!

Картинка и заголовок описывают существующий баг.
![image](https://user-images.githubusercontent.com/52084975/180656444-3d820657-3760-4fc1-87df-f7c134112e0f.png)

Чтобы воспроизвести ошибку вставть код ниже в [упражнение 3](https://sicp.hexlet.io/ru/exercises/3#editor):
```
#| BEGIN (Введите свое решение) |#
(define (square x)
  (* x x))

(define (solution x y z)
  (cond ((and (x < y) (< x z)) (+ square(z) (square y)))
        ((and (< y x) (< y z)) (+ (square x) (square z)))
        ((and (< z y) (< z x)) (+ (square y) (square x)))
        (else (+ (square x) (square y))))
  )
#| END |#
```

**Comment by pppershin** [comment]
Кажется нашел в чем проблема :thinking:
можно просто добавить `overflow-auto` в div card тогда скрол будет появляться, сейчас попробую оформить PR
(это будте первый PR поэтому могу потупить немного)

**Comment by fey** [comment]
fixed
