### ISSUE TITLE
Make a description of the default project in English

### ISSUE THREAD

**Issue by acidmaksim** [Hexlet/hexlet-sicp#1324]

**Comment by fey** [comment]
@acidmaksim :thinking: 
![image](https://user-images.githubusercontent.com/697178/182195730-4c34b83c-5e5d-4b18-ab1d-b2fe5a1fe6de.png)

**Comment by acidmaksim** [comment]
@fey Corrected

**Comment by ashikov** [comment]
@acidmaksim, а эта задача вроде готова? https://github.com/Hexlet/hexlet-sicp/blob/main/README.en.md 
Может закрыть этот issue?

**Comment by acidmaksim** [comment]
Нет, потому что сейчас, заходя в проект, описание на русском, а не на английском
<img width="1030" alt="image" src="https://user-images.githubusercontent.com/77053797/188288712-44d92ab8-9e69-461f-8922-d71d64b0c5f6.png">

**Comment by ashikov** [comment]
Может быть тогда попросим @mikhaylov-ya поревьювить и заменить русскую версию? Осталось вроде всего-ничего. 😇

**Comment by ashikov** [comment]
@mikhaylov-ya давай пока тут притормозим. Я глянул issue и по некоторым можно дополнить ридми. Сделаю это в русской версии, потом надо будет адаптировать эти изменения для английской версии ридми и вычитать, поправить ошибки. Это чтоб несколько раз не возвращаться к этому вопросу. Я напишу как можно будет редачить)

**Comment by ashikov** [comment]
Я сейчас перевожу проект на Vite. Так что можно подключать студентов, да.
