### ISSUE TITLE
Add sort for progress top page

### ISSUE THREAD

**Issue by fey** [Hexlet/hexlet-sicp#1336]
https://sicp.hexlet.io/ru/ratings/progress_top

Add sort by completed exercises or completed chapters

**Comment by pppershin** [comment]
Is this issue for frontend or for php developers? 🤔

**Comment by fey** [comment]
@pppershin boths, because sort should work on backend and table should contain links for sort

**Comment by vasilysmolin** [comment]
https://hexlet-heroku.herokuapp.com/ru/ratings/progress_top
Add sort by completed exercises or completed chapters

**Comment by fey** [comment]
@vasilysmolin там пустая табличка

**Comment by vasilysmolin** [comment]
> @vasilysmolin там пустая табличка
Выполнил сидеры на heroku сейчас данные появились, правда увидеть по сортировке получиться только по правой колонке в левой все числа одинаковые. Но там в целом алгоритм одинаковый.
