### ISSUE TITLE
Buttons and tabs disappear 

### ISSUE THREAD

**Issue by MAGLeb** [Hexlet/hexlet-sicp#1338]
If a lot of lines in editor tab, buttons and tabs disappear.

![image](https://user-images.githubusercontent.com/52084975/183892670-6425e60a-ea46-4f49-ab75-0ee06e9f5c17.png)

**Comment by pppershin** [comment]
@MAGLeb if you scroll down what do you see? Can you attach screenshot, please?

**Comment by pppershin** [comment]
The expected behavior is that we always should see tabs and buttons, am I right? :thinking:

**Comment by MAGLeb** [comment]
Yes, it seems to me that it will be more convenient, clearer, more logical.
