### ISSUE TITLE
Change the link in the button

### ISSUE THREAD

**Issue by acidmaksim** [Hexlet/hexlet-sicp#1341]
Change the link in the "Book" button to - https://web.mit.edu/6.001/6.037/sicp.pdf

<img width="648" alt="image" src="https://user-images.githubusercontent.com/77053797/185887547-3eed75de-3160-493d-ad7c-c54cce207590.png">

**Comment by Pathholder1806** [comment]
I would like to contribute to this issue

**Comment by Pathholder1806** [comment]
I guess this issue is already resolved
