### ISSUE TITLE
set-cdr!: unbound identifier (не импортируется sicp)

### ISSUE THREAD

**Issue by burenkov-anton** [Hexlet/hexlet-sicp#1342]
В упражнении 2.73 в тестовом коде используются функции библиотеки sicp. При попытке запуска решения эти функции не определяются.
![set-cdr!](https://user-images.githubusercontent.com/11513918/187030174-4e46fb26-e72e-4bc8-99b5-9f6149213fa7.png)

Локально в DrRacket всё запускается и тесты проходят

![set-cdrr](https://user-images.githubusercontent.com/11513918/187030198-6b0cff03-d5eb-42be-8dca-8cf745510a72.png)

Ранее вместо функций библиотеки sicp использовались функции библиотеки compatibility/mlist [коммит с изменением](https://github.com/Hexlet/hexlet-sicp/commit/cdcd03fd8f1c879d40d5b75e87e833dc11a53089) - данные функции также не определились.

![mlist](https://user-images.githubusercontent.com/11513918/187030276-92a5abf1-a851-46db-90d1-36d093518661.png)

Локально в DrRacket также всё работает

![mlr](https://user-images.githubusercontent.com/11513918/187030298-406868f6-eaf0-4f4d-8572-e06864c649cb.png)

**Comment by burenkov-anton** [comment]
Полагаю, что причины такие же что и в #1339

**Comment by burenkov-anton** [comment]
Похоже что нужно установить модуль sicp в сам racket через raco pkg install sicp

**Comment by fey** [comment]
Не удалось пофиксить, надо смотреть или билдпак или создавать info.rkt в проекте. Но я так делал и не помогло.
https://github.com/fey/heroku-buildpack-racket
Либо вообще отдельный сервис для проверки делать :с

**Comment by fey** [comment]
@tolyod

**Comment by burenkov-anton** [comment]
В упражнении 2.73 вернул библиотеку compability/mlist на сторону тестов и переместил в место где она может загрузиться , использовал set-mcdr! вместо set-cdr!, также пришлось заменить ряд других функций. Возможно получится переписать другие упражнения требующие функций из sicp с помощью встроенных библиотек, но возникает вопрос по поводу  совместимости, а также по поводу того, что в данном случае может требоваться использовании данных библиотек в коде решения - возможно понадобится указывать что в упражнении следует использовать функции из данных библиотек

**Comment by burenkov-anton** [comment]
Переписал тесты в 1.22 определил runtime, заменил if на when

**Comment by burenkov-anton** [comment]
Переписал решение в 3.22 на mcar, mcdr, mcons, set-mcdr! вместо car, cdr, cons, set-cdr!, в тесте упомянул что нужно использовать данные функции

**Comment by fey** [comment]
может сделать функции обертки над mcar/mcdr и так далее?

**Comment by burenkov-anton** [comment]
Сделал обертки в 3.22

**Comment by fey** [comment]
@burenkov-anton закрываем?

**Comment by burenkov-anton** [comment]
@fey
В целом можно закрыть. Переписывание тестов / добавление оберток, замена библиотек в процессе. Использование библиотеки sicp заменил использованием compatibility/mlist, lazy, lazy/force, racket/stream. Если что - то не получится переписать - открою другой issue.

**Comment by burenkov-anton** [comment]
Упражнения переписаны без использования библиотеки sicp
