### ISSUE TITLE
return 404 response if page not found (https://sicp.hexlet.io/pages/123)

### ISSUE THREAD

**Issue by fey** [Hexlet/hexlet-sicp#1343]
Add check if page (page's view file) not exists and return response with 404 status

**Comment by vasilysmolin** [comment]
Взял задачу

**Comment by vasilysmolin** [comment]
Не могу локально проблему воспроизвести. @fey 
![image](https://user-images.githubusercontent.com/28043582/187863369-6cb865d7-4515-4ecf-8d98-b748877c00e8.png)

**Comment by acidmaksim** [comment]
@fey подскажи, пожалуйста

**Comment by fey** [comment]
@vasilysmolin поэкспериментируй с переменными окружения, выставь конфиг как на проде

**Comment by vasilysmolin** [comment]
> @vasilysmolin поэкспериментируй с переменными окружения, выставь конфиг как на проде

Хорошо, попробую

**Comment by ashikov** [comment]
Работаю над этим issue. Хочу возвращать не только 404 статус, но и 404 вьюху. Это можно fallback роутом реализовать.
