### ISSUE TITLE
Add a page with all user comments

### ISSUE THREAD

**Issue by ashikov** [Hexlet/hexlet-sicp#1346]
Add a link in the [profile](https://sicp.hexlet.io/ru/users/91) and also go to the page with all comments from [here](https://sicp.hexlet.io/ru/ratings/comments_top), by clicking on the number in the "Number of comments" column

**Comment by vasilysmolin** [comment]
Взял в работу.
https://sicp.hexlet.io/ru/users/91/comments -вот такой сделать url со списком всех комментариев?

**Comment by vasilysmolin** [comment]
Ссылки добавил на страницах. Есть какие-то требования к отрисовке комментов?
Например: вывести к какой сущности принадлежит (с ссылкой на неё).
https://hexlet-heroku.herokuapp.com/users/1/comments

**Comment by ashikov** [comment]
А нужен ли нам ID в таблице? :grimacing: Может быть дату комментария лучше выводить? 

> вывести к какой сущности принадлежит (с ссылкой на неё).

Думаю это нужно сделать, так как в, собственно, списке не очень много смысла. А так можно перейти и глянуть контекст в котором был оставлен этот коммент.

**Comment by vasilysmolin** [comment]
https://hexlet-heroku.herokuapp.com/users/1/comments 
Сделал [pull request ](https://github.com/Hexlet/hexlet-sicp/pull/1375)
