### ISSUE TITLE
Исправить битые ссылки на главы из оригинала

### ISSUE THREAD

**Issue by zhabinka** [Hexlet/hexlet-sicp#1351]
Ссылки на оригинал статьи ведут на 404. Например, здесь https://sicp.hexlet.io/chapters/10 – выдаёт [404](https://mitpress.mit.edu/sites/default/files/sicp/full-text/book/book-Z-H-10.html#%_sec_1.1.8).

**Comment by fey** [comment]
можно поменять ссылки сюда https://xuanji.appspot.com/isicp/
