### ISSUE TITLE
Ссылка на перевод книги

### ISSUE THREAD

**Issue by zhabinka** [Hexlet/hexlet-sicp#1352]
Есть русские переводы, например, https://newstar.rinet.ru/~goga/sicp/sicp.pdf. В русскоязычной версии сайта в главном меню можно дать ссылку на эту книгу, для чтения.

**Comment by zhabinka** [comment]
На сайте https://newstar.rinet.ru/~goga/sicp/sicp.pdf не работает https, приходится настройки браузера менять.
Вот ещё один источник – https://mirror.yandex.ru/mirrors/ftp.linux.kiev.ua/docs/developer/general/sicp-ru/sicp-ru-screen.pdf

**Comment by ashikov** [comment]
Это готово

**Comment by Imam1325** [comment]
Это второе издание?

**Comment by fey** [comment]
> Это второе издание?

ВРоде бы да. Ссылка щас на гугл ведет.
