### ISSUE TITLE
Скрыть решения от пользователя, если он не решил задачу

### ISSUE THREAD

**Issue by zhabinka** [Hexlet/hexlet-sicp#1356]
Решение можно вывести по таймингу, как на CB, либо вообще не открывать, пока пользователь не решит задачу.

**Comment by fey** [comment]
https://github.com/Hexlet/hexlet-sicp/issues/1348

**Comment by Pavel-nk95** [comment]
Беру в работу!

**Comment by acidmaksim** [comment]
@Pavel-nk95 привет) Получается сделать задачу?
