### ISSUE TITLE
Исправить битые ссылки на упражнения

### ISSUE THREAD

**Issue by ashikov** [Hexlet/hexlet-sicp#1360]
Сейчас все ссылки ведут на 404
![Screenshot from 2022-09-22 21-04-40](https://user-images.githubusercontent.com/676554/191768763-46613835-9aee-4eb4-be46-38c3c79c191a.png)

**Comment by fey** [comment]
https://github.com/Hexlet/hexlet-sicp/issues/1351 fixed

**Comment by ashikov** [comment]
@fey это не пофикшено же.
Попробуй вот тут перейти на книжку, например: https://sicp.hexlet.io/ru/exercises/14

**Comment by ashikov** [comment]
https://github.com/Hexlet/hexlet-sicp/blob/main/resources/exercise-links.php
Вот тут надо пофиксить ссылки
