### ISSUE TITLE
Добавить в комментарии редактор с поддержкой Markdown

### ISSUE THREAD

**Issue by ashikov** [Hexlet/hexlet-sicp#1376]

**Comment by AslanAV** [comment]
возьму в работу

предлагаю summernote:
https://summernote.org/

https://github.com/summernote/summernote/

**Comment by ashikov** [comment]
@AslanAV тут есть прогресс?)

**Comment by fey** [comment]
wyiwsg не сильно нужен, проще сделать поддержку маркдауна на беке и рендер

**Comment by AslanAV** [comment]
Нашел такое решение:
- добавить пакет "spatie/laravel-markdown": "2.2.4"
- оборачивать вывод информации так `<x-markdown>`{{ ... }}`</x-markdown>`

теперь есть нюанс так как текст сохраняется в базу в формате markdown 
например `# Dillinger ## _The Last Markdown Editor`

то отображение на страницах 
`http://.../users/1/comments` // страница комментариев юзера
`http://.../`  // главная страница 

происходит либо ([скрин](https://disk.yandex.ru/i/NxD9btP59egvew))

- так не обернуто в `<x-markdown> `
`# Dillinger ## _The Last Markdown Editor`
т.е. видно форматирование markdown

- либо так обернуто в `<x-markdown> `
# Dillinger
## _The Last Markdown Editor

текст отображается не в едином стиле


пробовал удалить форматирование Markdown во вьюхах с помощью 
`preg_replace('/<([^>]+)>/', PHP_EOL, $content)`
`strip_tags()`
не получается удалить 

есть npm-пакет remove-markdown (здесь мне нужна помощь в подключении)
https://github.com/stiang/remove-markdown

**Comment by fey** [comment]
Такое не должно делаться в виде npm пакета. Т.е. если мы храним текст в md то должны уметь его обрабатывать (выводить в форматированном виде, либо без тегов), тут варантов несколько
1. дублировать контент (в чистом виде и с тегами)
2. хранить в 1 виде, выводить без тегов. 
Второй варант можно попробовать если заменить либу https://github.com/erusev/parsedown
