### ISSUE TITLE
Убрать inline стили из таблицы

### ISSUE THREAD

**Issue by ashikov** [Hexlet/hexlet-sicp#1378]
https://github.com/Hexlet/hexlet-sicp/blob/3a082aa88572981fed085c3a0155c2f0900c4393/resources/views/user/comment/index.blade.php#L12-L14

Возможно пригодится:
* https://getbootstrap.com/docs/5.0/utilities/api/#using-the-api
* https://getbootstrap.com/docs/5.0/utilities/sizing/#relative-to-the-parent

**Comment by seregad544** [comment]
взял задачу
