### ISSUE TITLE
Фильтрация по пользователю в списке решений

### ISSUE THREAD

**Issue by burenkov-anton** [Hexlet/hexlet-sicp#1384]
На данный момент в фильтре по пользователю в [Списке решений](https://sicp.hexlet.io/ru/solutions) можно выбрать только себя либо всех.
Свои решения можно посмотреть на странице [Прогресс](https://sicp.hexlet.io/ru/my) вкладка "Мои решения".
Логичнее или удалить данный фильтр по пользователю (может быть добавив ссылку на Мои решения или же чекбокс выполняющий фильтрацию), либо же добавить в фильтр всех пользователей, но особого смысла, как мне кажется, в добавлении всех пользователей нет.

![Desicions](https://user-images.githubusercontent.com/11513918/198068857-5472da71-3ea3-4e70-a32e-6834e53cbd58.png)

При просмотре страницы [Список решений](https://sicp.hexlet.io/ru/solutions) из-под неавторизованного пользователя в списке фильтрации только все пользователи, что по сути делает показ фильтра в данном случае бессмысленным

![Desicions2](https://user-images.githubusercontent.com/11513918/198071030-ef253c9a-25b7-41a9-a3cf-86458181473e.png)

**Comment by 62ng** [comment]
Я предлагаю вместо выпадающего select'а сделать текстовое поле и искать (фильтровать) пользователей по частичному совпадению имени. Если предложение принимается, то готов взять в работу.

**Comment by acidmaksim** [comment]
@ashikov подскажи, пожалуйста

**Comment by fey** [comment]
Выбор себя, либо всех был специально сделан, чтобы не выгружать 100500 юзеров и огромный список. Нужно подумать. как переделать страничку, чтобы можно было смотреть свои решения и решения других юзеров.

**Comment by 62ng** [comment]
Тогда сделаю как предложил. Вроде никому не противоречит.

Беру в работу.
