### ISSUE TITLE
Съехали элементы в nav

### ISSUE THREAD

**Issue by burenkov-anton** [Hexlet/hexlet-sicp#1385]
![nav2](https://user-images.githubusercontent.com/11513918/198693222-26f878d1-c15d-4786-8c8b-4aacd53715d7.png)

![nav](https://user-images.githubusercontent.com/11513918/198693239-66829657-7e17-4d28-8aa2-8f7d61a8d13a.png)

**Comment by sleepy-corpse** [comment]
Беру в работу
