### ISSUE TITLE
Реализовать карту сайта

### ISSUE THREAD

**Issue by ashikov** [Hexlet/hexlet-sicp#1391]
Нужно реализовать карту сайта в формате xml. В неё должны выгружаться все страницы на сайте включая главные, кроме исключений. 

Исключения: 

- Все страницы с код ревью (пример https://sicp.hexlet.io/ru/solutions/1397)
- Все профили пользователей (пример https://sicp.hexlet.io/ru/users/7029) 
- Все урлы начинающиеся с /en/ (пример https://sicp.hexlet.io/en/chapters/10) 

Сделать автоматическое обновление карты

**Comment by tigp** [comment]
@ashikov привет! почитал немного про XML карту сайта. 
хочу взять задачу, но есть пару вопросов:
1) мне вручную сделать или просто использовать ресурс, который сам делает карту сайта, а затем убрать лишнее или надо написать программу, которая будет в дальнейшем автоматически делать карту сайта?
2) в какой директории сохранить, к примеру, файл sicp-sitemap.xml?

**Comment by ashikov** [comment]
На самом деле карта уже есть, только нужно довести её до ума: https://sicp.hexlet.io/sitemap.xml

Реализована она с помощью пакета: https://github.com/Hexlet/hexlet-sicp/blob/3a082aa88572981fed085c3a0155c2f0900c4393/composer.json#L48

Попробуйте разобраться, там сейчас она через gists подгружается, но так быть не должно.

**Comment by tigp** [comment]
Хорошо, спасибо

**Comment by tigp** [comment]
Задача свободна! Не успеваю :(

**Comment by IgBuS** [comment]
@ashikov, привет!
хочу попробовать разобраться с этим

**Comment by IgBuS** [comment]
Здесь есть два варианта реализации.

Первый - отдавать карту по запросу каждый раз ее генерируя, тогда вызов генератора будет происходит при обработке роута. Выглядеть будет примерно вот так:
```
Route::get('generate-sitemap', function () {
    SitemapGenerator::create('https://app.test')
        ->writeToFile(public_path('sitemap.xml'));
});
```
Второй - вызывать генерацию по расписанию, например, ежедневно и по запросу отдавать файл из хранилища. Для этого варианта мне нужно получить адрес, куда можно было бы положить сгенерированный файл на боевом.

Думаю, что лучше, конечно, второй вариант. При этом я бы предложил избавиться от контроллера, потому что оба варианта обходятся без него и от тестов на этот контроллер. Видимо из-за тестов и используются gists.

P.S. Если для обсуждения таких вещей есть место получше, пожалуйста, сообщите мне об этом, буду иметь ввиду.

**Comment by acidmaksim** [comment]
@ashikov посмотри, пожалуйста

**Comment by ashikov** [comment]
Давай запилим второй вариант. Файл можно разместить в директории _public_.

**Comment by ashikov** [comment]
Тут 500 ошибка по ссылке с мапой: https://sicp.hexlet.io/sitemap.xml

**Comment by fey** [comment]
Github\Exception\RuntimeException: Not Found (Most recent call first)
File /app/vendor/knplabs/github-api/lib/Github/HttpClient/Plugin/GithubExceptionThrower.php:123
No data in file[View how to troubleshoot code context.](https://docs.rollbar.com/docs/code-context#section-troubleshooting-tips)
File /app/vendor/php-http/httplug/src/Promise/HttpFulfilledPromise.php:31 in Github\HttpClient\Plugin\GithubExceptionThrower::Github\HttpClient\Plugin\{closure}
File /app/vendor/knplabs/github-api/lib/Github/HttpClient/Plugin/GithubExceptionThrower.php:124 in Http\Client\Promise\HttpFulfilledPromise::then
File /app/vendor/php-http/client-common/src/PluginChain.php:46 in Github\HttpClient\Plugin\GithubExceptionThrower::handleRequest
File /app/vendor/php-http/client-common/src/PluginChain.php:61 in Http\Client\Common\PluginChain::Http\Client\Common\{closure}
File /app/vendor/php-http/client-common/src/PluginClient.php:87 in Http\Client\Common\PluginChain::__invoke
File /app/vendor/php-http/client-common/src/HttpMethodsClient.php:148 in Http\Client\Common\PluginClient::sendRequest
File /app/vendor/php-http/client-common/src/HttpMethodsClient.php:108 in Http\Client\Common\HttpMethodsClient::sendRequest

**Comment by fey** [comment]
ща гляну, мб гист неверно сделан

**Comment by fey** [comment]
После того, как я мержил, я вручную обновлял сайтмапу и все было ок.

**Comment by IgBuS** [comment]
то есть проблема с gist?

**Comment by fey** [comment]
Не знаю

**Comment by IgBuS** [comment]
потерялась строка в config/sitemap.php

```
'gist_id' => env('SITEMAP_GIST_ID'),
```
наверное дело в этом, а как лучше поступить в таком случае? создать еще fork, там поменять и сделать pull request?

**Comment by fey** [comment]
я не очень понимаю, что нужно поправить. Вы можете создать gist на гитхабе и использовать свои креды, локально или на любом облачном хостинге и подебажить, чтобы найти ошибку, вот)

**Comment by fey** [comment]
Т.е. ошибка в кредах может быть, а может в чем-то другом.
