### ISSUE TITLE
Обновить robots.txt

### ISSUE THREAD

**Issue by ashikov** [Hexlet/hexlet-sicp#1393]
Заменить содержимое https://sicp.hexlet.io/robots.txt

Нужно:

```text
User-agent: *
Disallow: */register
Disallow: */login
Disallow: */oauth/
Disallow: */users/
Disallow: /en/
Disallow: *?
```

**Comment by ashikov** [comment]
Это небольшая задача, которая появилась из сделанного SEO-аудита. Заменить строки не сложно, но можно ещё и разобраться, что этот файл делает и что значат строки в нём.

Если будет долго висеть, то конечно сам закрою. Тут кто успел, тот успел. :)

**Comment by maddbuzz** [comment]
я тут вроде должен отписать, что взял в работу

**Comment by ashikov** [comment]
Желательно отписаться конечно. Плюс можно в пулреквесте меншить issue, тогда он тут будет показываться.

**Comment by ashikov** [comment]
Сделано в #1397
