### ISSUE TITLE
не работают страницы с решениями

### ISSUE THREAD

**Issue by fey** [Hexlet/hexlet-sicp#1406]
На странице https://sicp.hexlet.io/solutions?page=5 находим решение, получаем 404

https://sicp.hexlet.io/solutions/6853

**Comment by AslanAV** [comment]
Привет, попробовал воспроизвести баг, локально все работает.

https://hexlet-sicp-aslan-av.herokuapp.com/solutions/5

**Comment by burenkov-anton** [comment]
Наверное вот это поведение -  https://github.com/Hexlet/hexlet-sicp/issues/1425

**Comment by burenkov-anton** [comment]
Решено в #1425 - вместо id решения подставлялось id пользователя, в случае если id пользователя было больше максимального id решения получали 404 (сейчас для пользователя 6853 корректно генерируются решения - например https://sicp.hexlet.io/ru/solutions/1388)
