### ISSUE TITLE
Разобраться зачем bootstrap подгружается через CDN и нужно ли оно

### ISSUE THREAD

**Issue by ashikov** [Hexlet/hexlet-sicp#1417]

**Comment by pershin-daniil** [comment]
## Разборки с `bootstrap`

- https://github.com/Hexlet/hexlet-sicp/commit/a79133b30f8bf3d14bd995ebdb3275cc319085d9 CDN был добавлен
- https://github.com/Hexlet/hexlet-sicp/pull/1441/commits/4acfdf4d7aacecc03f01ee68d21aef708c196ceb CDN удалил все норм — `bootstrap` импортирован в npm.

### Вывод

CDN удалил, а верстка осталась. Значит `bootstrap` где-то есть и работает. Смотрю в `package.json` — стоит `bootstrap: 5.1.3`. Значит CDN не нужен, что и требовалось доказать 👨🏼‍💻
