### ISSUE TITLE
Correct errors from validator w3

### ISSUE THREAD

**Issue by fey** [Hexlet/hexlet-sicp#142]
https://validator.w3.org/nu/?doc=https%3A%2F%2Fsicp.hexlet.io

**Comment by zhabinka** [comment]
@fey может знаешь, как автоматически закрыть issue, когда принимается пулреквест?

**Comment by fey** [comment]
@zhabinka https://help.github.com/en/github/managing-your-work-on-github/closing-issues-using-keywords#closing-an-issue-in-the-same-repository 
нужно сообщение с номером ишшуса в пулл реквесте (описании) или в коммите.

**Comment by zhabinka** [comment]
Так и сделал в комментарии к этому issue, но он не закрылся.

**Comment by fey** [comment]
Попробуй без слов между ключевыми словами ничего не писать, думаю тогда сработает.

**Comment by zhabinka** [comment]
Кажется, так и сделал. Вот такое имя у коммита и [пулреквеста](https://github.com/Hexlet/hexlet-sicp/pull/145)

> fix validator errors #142

**Comment by Yur-ok** [comment]
Взял в работу

**Comment by acidmaksim** [comment]
@fey Задача еще актуальна?

**Comment by fey** [comment]
угу

**Comment by artengin** [comment]
W3 ругался на счетчики в head

Переместил код счетчиков Яндекса и Google из head в начало body.

Если 'div' не находится внутри 'body', то браузер автоматически заворачивает его в 'body'.  
Код счетчика содержит 'div', при подключении которого к 'head' браузер завернул его в 'body', а затем мы сами создали основное 'body'. 

W3 считает это ошибкой.
