### ISSUE TITLE
remove react-codemirror2-react-17 and use codemirror from react directly

### ISSUE THREAD

**Issue by fey** [Hexlet/hexlet-sicp#1471]
Библиотека react-codemirror2-react-17 не очень то хорошо поддерживается. Судя по комментам в репо, проще использовать codemirror напрямую.

Поэтому нужно поисследовать возможность отказаться от eact-codemirror2-react-17

**Comment by antonDedyaev** [comment]
Беру в работу.

**Comment by ssssank** [comment]
#1491
