### ISSUE TITLE
Bug: fix invalid offset of save solution button's tooltip

### ISSUE THREAD

**Issue by fey** [Hexlet/hexlet-sicp#1481]
### Summary

При наведении курсором на кнопку сохранения решения тултип улетает влево

### Reproduction steps

```bash
1. В режиме гостя зайти в упражнение
2. Навести курсов на кнопку
3. Слева будет тултип
```

### Expected result

Тултип над кнопкой

### Actual result

Тултип слева.
![image](https://user-images.githubusercontent.com/697178/214701286-061d4054-06e2-4895-95a0-7a389f0de287.png)

### Browsers

Chrome

### OS

Linux

**Comment by likurg42** [comment]
Беру в работу

**Comment by likurg42** [comment]
Никак не могу воспроизвести этот баг
Протестировал на всех возможных размерах экрана, на
- Windows 11 - Chrome и Firefox
- Ubuntu 12.04 - Chrome и Firefox

Если ошибка все еще есть то пожалуйста опишите как она у вас появилась

**Comment by ssssank** [comment]
@fey и правда, не воспроизводится. Какая у тебя версия Linux и Chrome?

**Comment by fey** [comment]
Сейчас Версия 107.0.5304.121 (Официальная сборка), (64 бит) и тоже не воспроизводится.
Попробую еще понаблюдать, может быть мы что-то обновляли и починилось. 
Отдельно на винде проверю
