### ISSUE TITLE
Некорректный порядок в рейтинге пользователей (неверное количество баллов у пользователей)

### ISSUE THREAD

**Issue by burenkov-anton** [Hexlet/hexlet-sicp#1509]
На страницах  [Рейтинг пользователей](https://sicp.hexlet.io/ru/ratings/top) и  [прогресс](https://sicp.hexlet.io/ru/ratings/progress_top) некорректный порядок пользователей, также вижу что по какой - то причине сбился счетчик баллов, у многих пользователей решавших задачи и отмечавших главы он равен 0

**Comment by fey** [comment]
Недавно рефакторил работу с упражнениями - добавлял состояние (в процессе/завершено), возможно немного сломал этим рейтинг.
Скорее всего нужно будет передалть рейтинг, чтобы баллы начислялись и были в конечных цифрах, а не считались динамически.

**Comment by fey** [comment]
@burenkov-anton просьба чекнуть https://sicp.hexlet.io/ratings/top

**Comment by burenkov-anton** [comment]
Похоже на правду. Закрываю.
