### ISSUE TITLE
Добавить джобу для тестов на pgsql

### ISSUE THREAD

**Issue by fey** [Hexlet/hexlet-sicp#151]
Добавить дополнительную джобу тестирования на постгресе в CI / CD (Github Actions и, наверное в travis) для тестов приближенных к продакшену.
Т.е. должны идти тесты на sqlite и на постгресе.

**Comment by zhabinka** [comment]
Travis не нужен. GitHub Actions его полностью заменяет.

**Comment by fey** [comment]
чтобу добавили
