### ISSUE TITLE
Bug: Russian logo instead of english one in english locale

### ISSUE THREAD

**Issue by mootar** [Hexlet/hexlet-sicp#1516]
### Summary

https://github.com/Hexlet/hexlet-sicp/issues/1447
![bug_russian_logo_for_english_locale](https://user-images.githubusercontent.com/26491495/224976381-c01f1b84-bb33-4ab0-a011-adce4efdc86b.png)
### Reproduction steps

```bash
After site language switch to english
```

### Expected result

See english Hexlet logo

### Actual result

Logo is in russian

### Browsers

Chrome, Microsoft Edge

### OS

Windows

**Comment by fey** [comment]
Здесь нужна помощь дизайнера. Нам рисовали только ру лого :laughing: 
Если что могу svg поделиться, если кто-то будет рисовать лого.

**Comment by ssssank** [comment]
EN логотип обновили
