### ISSUE TITLE
Bug: Hexlet Editor link on the panel below gives 404 not found

### ISSUE THREAD

**Issue by mootar** [Hexlet/hexlet-sicp#1517]
### Summary

Everywhere within site

### Reproduction steps

```bash
-Scroll down
-Press Hexlet Editor
```

### Expected result

Get redirect to Hexlet Editor

### Actual result

Receive 404 not found

### Browsers

Chrome

### OS

Windows

**Comment by semenChe** [comment]
I will do it.

**Comment by fey** [comment]
https://github.com/Hexlet/hexlet-sicp/pull/1536
