### ISSUE TITLE
Bug: Missing link

### ISSUE THREAD

**Issue by mootar** [Hexlet/hexlet-sicp#1518]
### Summary

Either no link on a Code Basics or inactive

### Reproduction steps

```bash
-Scroll down
-Press Code Basics
```

### Expected result

To be able to get redirect to Code Basics site

### Actual result

Nonclickable text

### Browsers

Chrome, Microsoft Edge

### OS

Windows

**Comment by burenkov-anton** [comment]
[fixed](https://github.com/Hexlet/hexlet-sicp/commit/8f67f7b8a4f67a5ef5f8f1565407cf3be719ae3a)
