### ISSUE TITLE
Bug: Missing translation

### ISSUE THREAD

**Issue by mootar** [Hexlet/hexlet-sicp#1519]
### Summary

Missing translation for one of the links on the lower menu for english locale.
![bug_missing_translation](https://user-images.githubusercontent.com/26491495/224979134-fea783f6-cf48-4ca5-9b80-58fbbd431453.png)

### Reproduction steps

```bash
-Scroll down
-See link
```

### Expected result

channel Волонтеры in Telegram

### Actual result

канал Волонтеры в Telegram

### Browsers

Chrome, Microsoft Edge

### OS

Windows

**Comment by antonDedyaev** [comment]
Беру в работу

**Comment by antonDedyaev** [comment]
> @antonDedyaev давай просто Telegram
> 
> 

В смысле без волонтеров, просто одно слово Telegram?

**Comment by fey** [comment]
верно
