### ISSUE TITLE
Добавить описания упражнений

### ISSUE THREAD

**Issue by zhabinka** [Hexlet/hexlet-sicp#152]

**Comment by fey** [comment]
Чтобы добавить упражнение необходимо добавить его содержимое (код или картинка) по пути `resources/views/exercise/listing/#_#.blade.php`, а текстовое описание в `resources/lang/{locale}/sicp.php` под ключем `exercises.#.#` на соответствующем языке.

**Comment by romanoffivan** [comment]
А как быть с упражнениями вот такими?
```
Alyssa P. Hacker doesn't see why if needs to be provided as a special form. Why can't I just define it as an ordinary procedure in terms of cond?'' she asks. Alyssa's friend Eva Lu Ator claims this can indeed be done, and she defines a new version of if:

(define (new-if predicate then-clause else-clause)
  (cond (predicate then-clause)
        (else else-clause)))

Eva demonstrates the program for Alyssa:

(new-if (= 2 3) 0 5)
5

(new-if (= 1 1) 0 5)
0

Delighted, Alyssa uses new-if to rewrite the square-root program:

(define (sqrt-iter guess x)
  (new-if (good-enough? guess x)
          guess
          (sqrt-iter (improve guess x)
                     x)))

What happens when Alyssa attempts to use this to compute square roots? Explain. `
```
Тут код чередуется с текстом. А в данный момент добавлять можно только по принципу - описание -> код.

**Comment by fey** [comment]
Попробуй сделать вьюху без отдельного дескрипшена. Все, что должно быть переведено, положи в файлы переводов. Я попозже подумаю, как сделать красиво.

**Comment by fey** [comment]
@romanoffivan Переделал. 
Теперь достаточно создать файлы переводов, компонент-вьюху для описания задания, а там уже писать в удобнов виде.
Можно на это ориентироваться https://github.com/Hexlet/hexlet-sicp/pull/185/files

**Comment by romanoffivan** [comment]
отлично. буду потихоньку добавлять
