### ISSUE TITLE
Bug: No text wrapping for gap-free comments in Statistics on main page

### ISSUE THREAD

**Issue by mootar** [Hexlet/hexlet-sicp#1520]
### Summary

Text overlaps. User must be authorised to see.
![bug_no_text_wrapping_then_gap-free_in_statistics_on_main ](https://user-images.githubusercontent.com/26491495/224980260-fbdcbf40-cc95-45d9-ab44-d0174cc7842a.png)

### Reproduction steps

```bash
-Start random exercise
-Go to Discussions
-Submit random message with no gaps and over 150+ symbols
-Go to Main page
-Scroll down to Statistics
```

### Expected result

The text of the recent comment is properly wrapped. No overlap

### Actual result

Text in Activity log continues in a single string, overlaps with Latest comments column. In Latest comments this same text continues in a string making web-page wider. 

### Browsers

Chrome, Microsoft Edge

### OS

Windows

**Comment by bombom70** [comment]
взял в работу
