### ISSUE TITLE
Bug: Comments change is not displayed in Activity log in Statistics

### ISSUE THREAD

**Issue by mootar** [Hexlet/hexlet-sicp#1521]
### Summary

It isn't displayed in Activity log, displayed in Latest comments though. User must be authorised.
![bug_incorrect_updates_for_comments](https://user-images.githubusercontent.com/26491495/224985505-c0601759-40cd-4f68-b64b-bee1c0731649.png)
Related bug https://github.com/Hexlet/hexlet-sicp/issues/1522
### Reproduction steps

```bash
-Start random exercise
-Go to Discussion
-Submit random comment
-Press Edit under your comment
-Edit comment
-Press update
-Go to Main page
-Scroll down to Statistics
```

### Expected result

Both Activity log and Latest comments show your updated comment

### Actual result

See not updated comment in Activity log.
And see updated comment in Latest comments.

### Browsers

Chrome, Microsoft Edge

### OS

Windows

**Comment by algins** [comment]
Забрал
