### ISSUE TITLE
Bug: User icon dissapears from the hamburger-menu while changing resolution

### ISSUE THREAD

**Issue by mootar** [Hexlet/hexlet-sicp#1523]
### Summary

Bug: User icon dissapears from the hamburger-menu while changing resolution below 768 pxl width
![bug_breakpoint_768_pxl](https://user-images.githubusercontent.com/26491495/224987431-fefcca12-cec1-416a-94be-b3e0cf90c35a.png)
![bug_breaakpoint_below_768_pxl](https://user-images.githubusercontent.com/26491495/224987442-2f279fce-b87a-4fb7-9b7c-cf955dd064e6.png)
Issue persists for both locales

### Reproduction steps

```bash
-Open any page of sicp site
-Open Devtools
-Change screen resolution to between 768 and 991 pxl width
-Open hamburger-menu at the top of the page
-Change screen resolution to below 768 pxl width
```

### Expected result

User related icon is still present

### Actual result

User related icon dissapears

### Browsers

Chrome

### OS

Windows

**Comment by bombom70** [comment]
Взял в работу
