### ISSUE TITLE
Bug: Layout floats

### ISSUE THREAD

**Issue by mootar** [Hexlet/hexlet-sicp#1524]
### Summary

Layout floats on mobile version in portrait orientation for both locales
![bug_layout_floats_mobile_russian](https://user-images.githubusercontent.com/26491495/224989588-93c8fd0e-0101-47c4-bf02-9bb917780a0a.jpg)
![bug_layout_floats_mobile_english](https://user-images.githubusercontent.com/26491495/224989603-9848741a-6244-4473-a601-c015d6bda8da.jpg)

### Reproduction steps

```bash
-Open Main page as guest user
-Scroll down
```

### Expected result

We see proper margins being kept

### Actual result

Incorrect margins, thereby overlap

### Browsers

Chrome

### OS

Android 11

### Device

Pixel 2 XL Build/RP1A.201005.004.A1

**Comment by OddyHater** [comment]
@mootar 
Привет, хотел бы попробовать решить issue, но не могу воспроизвести проблему.
Подскажи, пожалуйста, по какой ссылке перейти.

**Comment by OddyHater** [comment]
Увидел, благодарю

**Comment by fey** [comment]
@OddyHater Посмотрите ПР https://github.com/Hexlet/hexlet-sicp/pull/1531 Там автор не прислал демо. 
Попроубйте задеплоить проект и посмотреть результат.

**Comment by ola-9** [comment]
@OddyHater @ddm14159 Привет! Скажите, пожалуйста, как успехи по этой задаче, нужна ли какая-то помощь?

**Comment by OddyHater** [comment]
@ola-9 Привет, возникли проблемы с установкой и развертыванием, пока разбираюсь, но выглядит объемно...
Если кто-то захочет выполнить пораньше - то будь оно так)

**Comment by fey** [comment]
@OddyHater я задеплоил то, что было. Можно демонстрировать не только разворачиванием проекта, но и просто HTML куда-нибудь на codepen например
Но там кажется все равно косяк на узких экрана. Я думаю, что блоки эти должны идти в одну колонку.

**Comment by ssssank** [comment]
Сейчас выглядит нормально. Закрываю ишьюс
![image](https://user-images.githubusercontent.com/17835285/233386594-dd1582e3-8fa7-44f2-8ba1-70229991c236.png)
