### ISSUE TITLE
Bug: при сохранении решения, появляется дополнительное оповещение "Не удалось сохранить решение"

### ISSUE THREAD

**Issue by Leenday** [Hexlet/hexlet-sicp#1562]
### Summary

Кликая на кнопку "сохранить" сохраняется решение, но выводится оповещение о том, что не удалось сохранить решение:
![image](https://github.com/Hexlet/hexlet-sicp/assets/47002584/f6040fe6-3d18-4365-b8ab-72c39a2b90cf)

### Reproduction steps

```bash
1. Ввести решение упражнения в редактор.
2. Кликнуть "Сохранить"
```

### Expected result

Оповещение "не удалось сохранить решение" не выводится, если решение сохранено.

### Actual result

Выводится оповещение "не удалось сохранить решение" и решение сохраняется.

### Browsers

Chrome

### OS

Mac

**Comment by fey** [comment]
Скорее всего сломалось из-за https://github.com/Hexlet/hexlet-sicp/commit/dbcb1c65d4a29cc4adc38be11d26d512ef887b21#diff-1b4fde47bab9ea5efbd570f3f60a0a9f1cae46ed24048ee092606028cc0ce9e1R30
