### ISSUE TITLE
Обновить логотипы

### ISSUE THREAD

**Issue by ssssank** [Hexlet/hexlet-sicp#1564]
### Problem description

Нам нарисовали логотипы в свг: 
[drive-download-20230615T103324Z-001.zip](https://github.com/Hexlet/hexlet-sicp/files/11756509/drive-download-20230615T103324Z-001.zip)

### Proposed solution

Взять логотипы и обновить их на сайте

**Comment by popovbm** [comment]
опять работать

**Comment by fey** [comment]
мы пытались сделать темную тему на основе бутстрапа. если честно не помню, сделали. 
Нужно учесить, что логтип должен менять цвет в зависимости от темы.

**Comment by fey** [comment]
ага
