### ISSUE TITLE
Bug: Ширина комментария в последних комментариях на первой странице

### ISSUE THREAD

**Issue by burenkov-anton** [Hexlet/hexlet-sicp#1574]
### Summary

Комментарий на первой странице занимает слишком большую ширину и требует прокрутки
На 2ой и 3ей страницах такой проблемы нет
![lastcomments](https://github.com/Hexlet/hexlet-sicp/assets/11513918/1ed82906-1529-47a9-b566-d824a126e521)

### Reproduction steps

```bash
Перейти на Последние комментарии - https://sicp.hexlet.io/ru/comments или на https://sicp.hexlet.io/ru/comments?page=1
```

### Expected result

Контент по ширине отображается без скроллинга

### Actual result

Контент по ширине отображается со скроллингом

**Comment by algins** [comment]
Возьму на работу
