### ISSUE TITLE
Не прогружается логотип  

### ISSUE THREAD

**Issue by AavadaKedavra** [Hexlet/hexlet-sicp#1578]
### Summary

На странице о проекте https://sicp.hexlet.io/ru/pages/about не прогружается лого
Тот же самый эффект наблюдается в разделах: Оглавление, Упражнение, Рейтинг и всех их подразделах 

### Reproduction steps

```bash
Открыть https://sicp.hexlet.io/ru/pages/about
Открыть https://sicp.hexlet.io/ru/chapters
Открыть https://sicp.hexlet.io/ru/exercises
Открыть https://sicp.hexlet.io/ru/ratings/top
```

### Expected result

Логотип сайта должен отображаться 

### Actual result

Логотип сайта не прогружается 
![image](https://github.com/Hexlet/hexlet-sicp/assets/126116401/b87cdd7a-7237-4135-8ac6-a0f16de36ffe)

### Browsers

Chrome, Opera

### OS

Windows

**Comment by fey** [comment]
https://github.com/Hexlet/hexlet-sicp/commit/02ea9a3d7da3a506c35fd86edcb3724f867f15e5
