### ISSUE TITLE
Bug: Есть возможность создать аккаунт с невалидным емейлом

### ISSUE THREAD

**Issue by alexidude** [Hexlet/hexlet-sicp#1599]
### Summary

Есть возможность создать аккаунт с невалидным емейлом

### Reproduction steps

```bash
1. Открыть страницу регистрации https://sicp.hexlet.io/register
2. Ввести не валидный email "sic@g.ra"
3. Ввести корректное имя 
4. Ввести корректный пароль
5. Продублировать корректный пароль в поле "Confirm password"
6. Нажать "Sing up"
```

### Expected result

Регистрации не произойдет, поле "email" выдаст ошибку

### Actual result

Пользователь зарегистрируется 

### Browsers

Chrome

### OS

Windows

**Comment by fey** [comment]
>sic@g.ra

можете скинуть инфу, чтобы было понимание, почему данный емейл невалиден?

**Comment by alexidude** [comment]
@fey Да, конечно 1) емейла не существует; 2) он написан с ошибками

**Comment by fey** [comment]
@alexidude насчет несуществующего - с этим понятно. Тут по идее должна быть валидация емейла (подтверждение через письмо). А какие ошибки? Я просто не вижу их сходу

**Comment by alexidude** [comment]
Я почему-то думал, что если домен в емейле некорректно указан, то это ошибка)

**Comment by fey** [comment]
есть стандарты для валидации емейлов. Например такой емейл, который вы указали - вполне валиден. 
Правда есть еще емейлы с нелатинскими символами - и там иногда могут особенности быть.
