### ISSUE TITLE
Bug: Ссылка работает через раз

### ISSUE THREAD

**Issue by dinzhev** [Hexlet/hexlet-sicp#1621]
### Summary

Ссылка работает через раз, в RU локализации

### Reproduction steps

```bash
1. На главной странице перейти по ссылке "Книга"
2. Обновить страницу
```

### Expected result

Доступный конткет по ссылке

### Actual result

Ошибка 404

![image](https://github.com/Hexlet/hexlet-sicp/assets/43177015/339527a5-7ba5-45ca-b4ca-613c973a45cc)

### Browsers

Chrome

### OS

Windows

**Comment by dinzhev** [comment]
Причём ошибка может как сразу вылезти, так и после нескольких обновлений страницы

**Comment by SpaYkeR696** [comment]
А сама ссылка на пдф рабочая?

**Comment by fey** [comment]
fixed https://github.com/Hexlet/hexlet-sicp/commit/cacafdcfab966238b18e2f759fe80854457802ab
