### ISSUE TITLE
Bug: Placeholder "Поле ввода сообщения (поддерживается markdown)" выходит за границы div контейнера с классом "col-md-6 mt-2" на вкладке "обсуждение", в разделе упражнения

### ISSUE THREAD

**Issue by Sh3rlock-git** [Hexlet/hexlet-sicp#1630]
### Summary

Placeholder "Поле ввода сообщения (поддерживается markdown) выходит за границы div контейнера с классом "col-md-6 mt-2" на вкладке "обсуждение", в разделе упражнения, на брекпоинтах  375*667 (книжная и альбомная ориентация)

### Reproduction steps

```bash
1. Авторизоваться в учетной записи
2. Перейти на вкладку "Упражнения"
3. Выбрать из списка любое упражнение, например https://sicp.hexlet.io/ru/exercises/7#exercise-discussion
4. Перейти на вкладку "Обсуждение"
5. Открыть DevTools (Toggle Device Toolbar)
6. Выбрать из списка устройств Iphone SE в книжной ориентации
7. Перевести экран в альбомную ориентацию
```

### Expected result

Placeholder "Поле ввода сообщения (поддерживается markdown)" не выходит за границы поля ввода текста

### Actual result

Placeholder "Поле ввода сообщения (поддерживается markdown)" выходит за границы div контейнера с классом "col-md-6 mt-2"

**Environment**
OS Windows 10 Pro
Yandex.Browser 24.4.4.1168 (64-bit)
![sicp_hexlet_placeholder](https://github.com/Hexlet/hexlet-sicp/assets/158310621/f7a2e771-a9a8-4c6d-8553-ccce988969e8)

**Comment by VictoryPashkova** [comment]
Возьму задачу

**Comment by artengin** [comment]
Исправил 'bug'
Разрешил перенос текста на другую строку в placeholder
