### ISSUE TITLE
Нельзя выйти из своей учетной записи

### ISSUE THREAD

**Issue by mrBasyuk** [Hexlet/hexlet-sicp#1632]
### Summary

При попытке выйти из учетной записи-сайт выдает ошибку.

### Reproduction steps

```bash
1. Зарегистрированному пользователю зайти на сайт
2. Выйти из своей учетной записи
```

### Expected result

Пользователь выйдет из своей учетной записи

### Actual result

Сайт выдает ошибку.Пользователь не может выйти из своей учетной записи
![4YDZT9qfg5U](https://github.com/Hexlet/hexlet-sicp/assets/167098827/fb9bfabf-811b-4778-9bfc-723b177bbef1)
![dNnciy-fFxg](https://github.com/Hexlet/hexlet-sicp/assets/167098827/8bec702a-7e81-4c46-8709-d4d09559c967)

### Browsers

Chrome

### OS

Windows

**Comment by fey** [comment]
https://github.com/Hexlet/hexlet-sicp/commit/b7b742107b311e249eac5fae3af3d946ba3a38b9
