### ISSUE TITLE
Bug: Не верная ссылка и название кнопки 'База знаний' на главной странице

### ISSUE THREAD

**Issue by 2laexe** [Hexlet/hexlet-sicp#1633]
### Summary

Ссылка на кнопке 'База знаний' "https://ru.hexlet.io/knowledge" на главной странице приводит к редиректу на "https://ru.hexlet.io/webinars". на странице https://ru.hexlet.io/ кнопка с URL "https://ru.hexlet.io/webinars" называетcя "Бесплатно"
![image](https://github.com/Hexlet/hexlet-sicp/assets/100873772/65329f4d-2acc-41c6-80f0-c89f2d81b772)
![image](https://github.com/Hexlet/hexlet-sicp/assets/100873772/785c6b70-68fa-4ec1-af56-161f1fedcce7)
![image](https://github.com/Hexlet/hexlet-sicp/assets/100873772/6a291483-1aa1-4eb4-86f1-aea0172e3fe2)

### Reproduction steps

```bash
1. Перейти на главную страницу сайта https://sicp.hexlet.io/.
2. Кликнуть на ссылку "База знаний".
3. Происходит редирект на страницу вебинаров.
```

### Expected result

Кнопка должна называться "Бесплатно" и вести напрямую на страницу вебинаров https://ru.hexlet.io/webinars.

### Actual result

Кнопка называется 'База знаний' и ведет на https://ru.hexlet.io/knowledge, после чего происходит редирект на страницу вебинаров https://ru.hexlet.io/webinars.

### Browsers

Chrome

### OS

Windows

**Comment by Smol-An** [comment]
взяла

**Comment by 2laexe** [comment]
> взяла

Сайт обновили, теперь называется "Учиться бесплатно"
![image](https://github.com/Hexlet/hexlet-sicp/assets/100873772/8d8ddf14-8395-4e26-82e1-763308444a85)
![image](https://github.com/Hexlet/hexlet-sicp/assets/100873772/f9a9e435-69a5-4014-a65e-cf05dc325b92)
