### ISSUE TITLE
TODO: дизайн и фронт

### ISSUE THREAD

**Issue by fey** [Hexlet/hexlet-sicp#18]
* Страница регистрации
* Страница пользователя (список глав с чекбоксами для отметки о прочитанном)

Пожелания приветствуются, если что-то берете в работу, отметьтесь. Список может измениться.

**Comment by grozwalker** [comment]
давай возьму профиль.
Сделаю, как на хекслете:
- слева фото, под ним имя
- справа большая область с вкладками

**Comment by honeydev** [comment]
Возьму страницу регистрации.

**Comment by fey** [comment]
Андрей оставил комментарии по поводу верстки. В основном к классу `.col` который не нужен. Просьба глянуть https://github.com/Hexlet/hexlet-sicp/pull/33/files/4bee2caada81671b52a6a2623ad612bb013aa453

**Comment by BabayevEldar** [comment]
Еще осталось чего взять

**Comment by fey** [comment]
@BabayevEldar если это вопрос, то нужно нарисовать единое меню-навигацию, в которой будет регистрация/логин + логин по гитхабу, а после логина кнопка на просмотр/отметку глав. 
Ну и страничка с главами, нужно посмотреть что есть щас.
