### ISSUE TITLE
Github-style чарт активностей

### ISSUE THREAD

**Issue by fey** [Hexlet/hexlet-sicp#186]
Для главной страницы сделать чарт активностей как на гитхабе, Кодбаттле, Хекслете., как тут
https://codebattle.hexlet.io/
https://ru.hexlet.io/u/feycot
https://github.com/fey

Для вдохновления - 
https://codepen.io/Kaperstone/pen/wrZqOV
https://codepen.io/ire/pen/Legmwo

Кубики должны закрашиваться по количеству записей в логе активности за этот день.

**Comment by fey** [comment]
Запилил в #187 
Пока оставлю открытым для обсуждения/улучшения.

**Comment by smcube** [comment]
Стоит добавить месяцы и недели.

**Comment by zhabinka** [comment]
Надо бы добавить название месяцев и дней недели.

**Comment by fey** [comment]
Пока оставим как есть, потом придумаем, как можно улучшить текущий чарт.
