### ISSUE TITLE
Добавить возможность удалять упражнения из списка пройденных

### ISSUE THREAD

**Issue by zhabinka** [Hexlet/hexlet-sicp#196]
После того, как упражнение отмечено, его уж нельзя отменить. Почему? А если пользователь, например, ошибся?

**Comment by fey** [comment]
Не подумол.
Надо на каждый чекнутый квадратец добавить ujs кнопку удаления с алертом.

**Comment by zhabinka** [comment]
Вообще главы сохраняются по кнопке Save, а упражнения автоматически. Непоследовательно выходит.

**Comment by fey** [comment]
Автоматически это как? Там надо на квадратик нажать, чтобы сохранить.
У глав есть названя, у упражнений нет. Если вынести упражнения отдельно и сохранять чекбоксом (как главы), то выглядит некрасиво. Поэтому сохранение по 1 штуке. По идее должно проверить код в репе и засчитать упражнение

**Comment by fey** [comment]
Добавил удаление
