### ISSUE TITLE
Добавить названия глав/переводы на https://sicp.hexlet.io/ru/exercises

### ISSUE THREAD

**Issue by fey** [Hexlet/hexlet-sicp#212]

**Comment by philatm** [comment]
Названия упражнение  мне кажется не придумаешь. Что если будет вот так?
![hexlsicpex](https://user-images.githubusercontent.com/10869388/79410558-35b63680-7fba-11ea-89cd-979c4b20cfaa.png)

**Comment by fey** [comment]
Хотя в начале так. По названиям глав надо все равно подумать, может какое-то описание сойдте.
