### ISSUE TITLE
Исправить стили чарта активностей

### ISSUE THREAD

**Issue by arkadiy93** [Hexlet/hexlet-sicp#214]
Когда экран <1200 px, чарт активности вылезает за область видимости и ломает стили.
<img width="1164" alt="Screenshot 2020-04-10 at 14 41 00" src="https://user-images.githubusercontent.com/23264453/78991567-83095280-7b39-11ea-81cc-9ec13c0e4196.png">
<img width="941" alt="Screenshot 2020-04-10 at 14 41 19" src="https://user-images.githubusercontent.com/23264453/78991577-87ce0680-7b39-11ea-869a-f1fa93b247c0.png">

**Comment by fey** [comment]
Два варианта:
сделать адаптивныки, как на хекслете (уменьшается масштаб квадратов)
Как на Гитхабе (немного уменьшается масштаб, если слишком узкий экран, то прячутся первые квадраты

**Comment by fey** [comment]
#186
