### ISSUE TITLE
Невозможно поставить галочку на саму главу

### ISSUE THREAD

**Issue by maximtop** [Hexlet/hexlet-sicp#215]
Невозможно поставить галочку на саму главу на этой странице, только на сами упражнения
https://sicp.hexlet.io/my

![image](https://user-images.githubusercontent.com/17272769/79073082-277fc600-7ced-11ea-8f13-73dc76654b9b.png)

**Comment by fey** [comment]
Какой браузер? Главы и упражнения сохраняются отдельно.
Главы - отмечаешь галочками, жмешь кнопку сохранить (отправка формы).
Упражнения - сразу отмечаются.

**Comment by maximtop** [comment]
Я понял
Вводит в заблуждение то, что упражнения умеют сами помечаться, а главы не умеют
