### ISSUE TITLE
Прокачать главную страницу

### ISSUE THREAD

**Issue by fey** [Hexlet/hexlet-sicp#220]
Можно добавить на главную страницу различную статистику:
Оставленных комментариев, пройденных упражнений, глав. Сколько человек выполнили все задания и главы.

**Comment by fey** [comment]
feycot:banana:  14:14
Привет, там не то что бы объемно, просто комплексная проблема с переделкой главной странички
14:15
Т.е. можно в уголок зафигарить блок и туда добавить типа "сегодня решили N упражнений, оставили N комментариев, N всего осиляторов"
14:16
Т.е. по сути несколько запросов к бд составить и циферки вывести на страницу. Но! Надо подумать как лучше это сделать. Потому что ща статистика находится на нижней части страницы, т.е. её нужно скросллить, чтобы увидеть ту статистику и активность, что есть
14:18
Как вариант можно уменьшит отступ от навбара и h1 чтобы поднять контент, поменять сетку, чтобы описание-подзаголовок ушел влево, поднять боковую сторону и вставить туда статистику :thinking_face:

**Comment by fey** [comment]
feycot:pepe_hype:  3 days ago
https://hexlet-sicp-test.herokuapp.com/ru
https://sicp.hexlet.io/ru
Ребзи, у нас тут навигация тюнится в сикп. Потыкайте, посмотрите, понятно ли что куда нажимать. Пишите в тред если че (edited) 
:100:
1


Glagius  3 days ago
Крутые перцы!
На все руки мастера. Свои Руби / Питон / Ноду пишут.
image.png 
image.png



Glagius  3 days ago
Может просто названия проектов и в скобках стек?
image.png 
image.png



feycot:pepe_hype:  3 days ago
Ну можно, присылай пулл реквест :batya:

Glagius  3 days ago
ПхП не моё :slightly_smiling_face:

feycot:pepe_hype:  3 days ago
Там ток текст поменять, можно даже проект не разворачивать, а прямо на гитхабе поправить

Glagius  3 days ago
И еще момент - может сразу тыкнуть пальтсем, ЧТО именно меняется? Я посмотрел навигацию внизу / наверху, вроде проблем не возникло, но хз что именно хотели проврить.

Glagius  3 days ago
Там ток текст поменять, можно даже проект не разворачивать, а прямо на гитхабе поправить
Это скучно :slightly_smiling_face:

feycot:pepe_hype:  3 days ago
сейчас например менюшка вложена в дропдаун (сверху слева), а будет как нормальная навигация

Glagius  3 days ago
Мне как стороннему человеку непонятно назначение этих зелёных кубиков. Вроде в гитхабе так показывают МОЮ активность. Но я не зареган.
image.png 
image.png



feycot:pepe_hype:  3 days ago
image.png 
image.png



Glagius  3 days ago
А я картинок накидаю :slightly_smiling_face:
image.png 
image.png



feycot:pepe_hype:  3 days ago
Что еще  можно добавить?

Glagius  3 days ago
Призыва "отметить прочитанное" нет. Только моё любопытство сподвигло тыкнуть на кнопку. И всё равно попал на регистрацию.
image.png 
image.png



feycot:pepe_hype:  3 days ago
@mshkv Андрей, призови, пожалуйста, Алексея, чтобы если заскучает посмотрел на наше безобразие

mshkv:hexlet:  3 days ago
@alshad призвал

Glagius  3 days ago
https://hexlet-sicp-test.herokuapp.com/ru/chapters
Я бы на этой странице, справа / слева добавил блок с оглавнением.
Громадный список с главами вгоняет в уныние, не хочется прокручивать вниз.

Glagius  3 days ago
Либо сделать главы сворачивающимися, потому что там текста и нет толком, только список ссылок.

Glagius  3 days ago
Кто эти люди? Кто стащил запятые?
image.png 
image.png



Glagius  3 days ago
Зачем мне прокручивать вниз, чтобы узнать что есть добавленные упражнения?
image.png 
image.png



Glagius  3 days ago
Если меняю локаль, меня сбрасывает на основной роут.

feycot:pepe_hype:  3 days ago
Зачем мне прокручивать вниз, чтобы узнать что есть добавленные упражнения?
это как (edited) 

Glagius  3 days ago
Выше я показал. У меня весь список упражнений не влазит на страницу, а если сделать масштаб больше, то тем более не влезет. Да и уйма "пустых" мест явно характеризует "недоделаность" проекта.

Glagius  3 days ago
Нужны ли ссылки на несуществующие упражнения?
И как его кто-то завершит, если его нет?))
image.png 
image.png



feycot:pepe_hype:  3 days ago
Просто упражнение можно отметить прочитанным, но текста пока нет. Там ссылка на сайт мит есть. Т.е. можно открыть упражнение, решить

Glagius  3 days ago
Может тогда ссылку сделать ссылкой а не иконкой? Я вот хз, это оформление такое или реально ссылка на сторонний ресурс.

Glagius  3 days ago
Пока так. Пойду, дальше поработаю.

feycot:pepe_hype:  3 days ago
да, можно вместо "нет описания" вставить ссылку на мит @alshad

feycot:pepe_hype:  3 days ago
Спасибо, фидбек полезен (edited) 
:cat_typing:
1


Serhii Shramko  3 days ago
https://tppr.me/8AuhM про кнопку согласен 100. Не сразу понял, как начать.
Потому как я думал это, что то типа курсов и искал кнопку начать. Ведь я ще ничего не читал и про СИКП не знаю
tppr.metppr.me
Public Screenshots - Screenshot_2020-07-14 10-08-51 (262 kB)
https://tppr.s3.amazonaws.com/uploads/515e8fb7a9bab162a4c805fbf45ed0b4.jpg

Serhii Shramko  3 days ago
Начать/Начать обучение/Начать прохождение что-то в этом роде было бы лучше имхо

Evgeny Malafeev  3 days ago
Эльдар разошёлся)

Glagius  3 days ago
Та неее, просто ребятам помочь захотел :slightly_smiling_face:

**Comment by fey** [comment]
![image](https://user-images.githubusercontent.com/697178/87813364-35f4f500-c87b-11ea-8496-24e6902f250f.png)

![image](https://user-images.githubusercontent.com/697178/87813351-2bd2f680-c87b-11ea-8501-d35fdf88d1e9.png)

![image](https://user-images.githubusercontent.com/697178/87813379-3f7e5d00-c87b-11ea-87f3-97f46b7c6821.png)
"Зачем мне прокручивать вниз, чтобы узнать что есть добавленные упражнения?"
![image](https://user-images.githubusercontent.com/697178/87813388-44431100-c87b-11ea-9244-7437ebc7cf1d.png)

**Comment by fey** [comment]
"Зачем мне прокручивать вниз, чтобы узнать что есть добавленные упражнения?"
![image](https://user-images.githubusercontent.com/697178/87813425-58870e00-c87b-11ea-8df1-330b98774d69.png)

**Comment by ashikov** [comment]
@acidmaksim тут бы сделать краткие конспекты из диалогов, чтобы было проще войти в контекст

**Comment by ashikov** [comment]
@acidmaksim

**Comment by acidmaksim** [comment]
@ashikov сегодня сделаю

**Comment by AslanAV** [comment]
Привет, я сделал примерно
https://hexlet-sicp-aslan-av.herokuapp.com/
доступно залогиненным пользователям.

Для гостя выводится другая страница, и там другое оформление, там есть карусель, 
есть другая статистика

- 129 chapters
- 356 exercises
- 12 users
- 29 comments

по гостевой надо больше уточнений, что убрать

**Comment by fey** [comment]
Для гостя по сути выводится лендинг, который должен приглашать его зарегистрироваться и начать обучение. 
На самом деле в случае лендинга надо подумать о том. как сделать супер-пупер лендинг.

**Comment by fey** [comment]
@acidmaksim напоминалка про то, чтобы описать идеи для главной

**Comment by acidmaksim** [comment]
@fey мы с Асланом уже все обсудили, он скинул прототип

**Comment by acidmaksim** [comment]
@AslanAV ты немного не так сделал. Нужно было поднять весь текст на первом экране лендинга, а в появившемся месте, как раз добавить статистику

**Comment by fey** [comment]
В ишшусе-то контекста нет)
Точнее этот ишшус - это обсуждение. А так если надо что-то конкретное сделать, можно создать новый с техническим заданием

**Comment by AslanAV** [comment]
точно, нужно, а то у меня плывет все в голове :) 
https://hexlet-sicp-aslan-av.herokuapp.com/

подправил статистику, раньше выводило общее количество всех заданий и упражнений)))), сейчас отмеченные как пройденные и решенные, выводятся на главную

**Comment by fey** [comment]
![image](https://user-images.githubusercontent.com/697178/203051800-6cf7dbe9-cb28-4583-920e-cd27ae386fa5.png)
текст в карусели не вмещается.

**Comment by fey** [comment]
По лендингу. Нам делали новый дизайн, нужно его кстати использовать - https://github.com/Hexlet/hexlet-sicp/tree/main/design
Но минус в том, что щас кнопка призыва к действию находится на 2 экране. Можно попробовать своими силами это поправить

**Comment by ssssank** [comment]
@fey а здесь ещё не всё?

**Comment by fey** [comment]
Да, думаю можно закрывать.
