### ISSUE TITLE
Выпадающий список в навбаре перекрывается списком глав в /my

### ISSUE THREAD

**Issue by fey** [Hexlet/hexlet-sicp#224]
![image](https://user-images.githubusercontent.com/697178/80127653-14eb7380-85ae-11ea-9ae7-9a0504167aeb.png)

**Comment by fey** [comment]
Проблема в списке, на странице упражнений тоже идет наслоение.

**Comment by zhabinka** [comment]
Наверное, можно закрыть issue.
