### ISSUE TITLE
Добавить навигацию в просмотр глав и упражнений

### ISSUE THREAD

**Issue by fey** [Hexlet/hexlet-sicp#272]
Добавить ссылки на предыдущее/следующее

**Comment by MityaDementiy** [comment]
@fey привет. А что именно здесь требуется? 

Вот здесь есть ссылки на предыдущую и следующую главы https://sicp.hexlet.io/ru/chapters/7 Надо добавить такие же в упражнения? https://sicp.hexlet.io/ru/exercises/7 Но это решено на стороне бэкенда насколько понимаю https://github.com/Hexlet/hexlet-sicp/commit/ecc9f461151ae19882a50f162042ee340db6ae69 

Или нужно сделать красивыми эти ссылки next/prev?

**Comment by fey** [comment]
Да, на главы я добавил навигацию. 
На упражнения не знаю как лучше сделать, также как с главами или как-то по другому. Например навигация давать ссылку на след упражнение в рамках главы (типа 1.1 .1.2 друг на ддрга ссылаются, а 1.2, 2.1 нет) 🤔  Ну и может на главах навигация стремная

**Comment by MityaDementiy** [comment]
На главах на стороне бэкенда определяются предыдущая и следующая. Здесь тоже надо на стороне бэкенда для консистентности получается?

**Comment by fey** [comment]
Да, там прост по айдишнику определяется
