### ISSUE TITLE
Добавить ссылку на MIT упражнения/главы на странице просмотров сущностей

### ISSUE THREAD

**Issue by fey** [Hexlet/hexlet-sicp#278]
Добавить ссылки первоисточник на mit.edu
Пример https://mitpress.mit.edu/sites/default/files/sicp/full-text/book/book-Z-H-10.html#%_thm_1.1

**Comment by Laserroy** [comment]
@fey 
Как это должно выглядеть?
Нужно спарсить, добавить и дергать из БД  или тупо вручную прописывать?

**Comment by fey** [comment]
Надо подумать, Как вариант спарсить, положить в файлик для начала
