### ISSUE TITLE
Не работает авторизация через Гитхаб

### ISSUE THREAD

**Issue by InfluxOW** [Hexlet/hexlet-sicp#288]
После нажатия кнопки и входа в аккаунт редиректит на 404 на Гитхабе

**Comment by fey** [comment]
А ты её у себя проверял или на sicp.hexlet.io?

**Comment by InfluxOW** [comment]
А, да, понял, только локально не работает, я затупил

**Comment by fey** [comment]
Её надо настроить, ну и инструкцию наверное добавить 🤔
