### ISSUE TITLE
метод отмечания прочитанных глав

### ISSUE THREAD

**Issue by baltun** [Hexlet/hexlet-sicp#31]
метод, который получает массив прочитанных глав и в соответствии с ним обновляет таблицу прочитанных глав

**Comment by grozwalker** [comment]
- Почему сделал сохранение по одной:
логика была в том, что даже если не будет никакого аякса, то при нажатии на чекбокс мы будем сразу отправлять запрос на прочитанность главы и сохранять его. Если добавить аякс, то будет тоже самое, но уже без сохранения. Минус отправки массива (на мой взгляд), что ты натыкал главы и потом тебе надо будет нажать кнопку сохранить, а это можно забыть или что-то такое. Ну и если будет аякс, то при каждом клике надо будет собирать массив глав и их отправлять, мне показалось так хуже.


- Насчет названия метода согласен. Но логика была типа: "пользователь прочитал главу"

- Насчет вынесения логики в отдельный слой. Наверное, я честно говоря не силен в таких вещах. И пока там всего один метод сохранения и руководствуясь той статьей про ооп, что ненадо делать чего-то лишнего - оставил в модели. Если что-то надо с этим сделать, то поправлю.
