### ISSUE TITLE
Некорректный подсчет глав

### ISSUE THREAD

**Issue by burenkov-anton** [Hexlet/hexlet-sicp#311]
В рейтинге (https://sicp.hexlet.io/ru/ratings/progress_top) и в статистике пользователя неверно считаются прочитанные главы - считаются главы только начиная с нумерации от 3его уровня, которые и отмечаются, например 1.1.1 Выражения, но не 1.1 Элементы программирования или 1 Построение абстракций с помощью процедур. Но главы с 1ого и 2ого уровня учитываются в общем количестве глав - "Прочитано глав из 129"
То есть сейчас можно отметить 101 главу из 129 максимум.
Можно или игнорировать главы 1 и 2ого уровня при подсчете всего, либо например неявно отмечать эти главы когда прочитаны все подглавы.

**Comment by Laserroy** [comment]
Можно давать экстра поинты за полную главу. Если че получится,  то выставлю на обсуждение.
