### ISSUE TITLE
Форма сброса пароля: поле Confirm Password помечается валидным, хотя не должно

### ISSUE THREAD

**Issue by ashikov** [Hexlet/hexlet-sicp#335]
Если перейти по ссылке из письма для сброса пароля и **не заполняя форму** нажать на кнопку _Reset Password_, то поле ввода подтверждения пароля помечается как валидное.

[Скриншот](https://www.dropbox.com/s/ox11nddn6rqalh2/reset_password_is_valid.png?dl=0)

**Comment by ashikov** [comment]
@fey Привет! Может есть какие правила по оформлению issue? Я это делаю второй раз, так что если не верно тайтл написал или еще что, то поменяю. :)

**Comment by fey** [comment]
Не, нету. Главное, чтобы было понятно, в чем проблема.
