### ISSUE TITLE
Подключить лендинг 

### ISSUE THREAD

**Issue by fey** [Hexlet/hexlet-sicp#444]
Туть - #443

Подключить лендинг, переделать на шаблонизатор.
Показывать только незарегистрированным пользователям.

**Comment by AlexeyShobanov** [comment]
Что-то я немного подвис с этой задачей. Я правильно понимаю, что лендинг нужно переписать в шаблонизатор и потом передалать роутинг так, что он будет домашней страницей для неавторизованных пользователей. Как-то с роутингом я запутался.

**Comment by fey** [comment]
Да, типа того.

В welcome controller обычный иф, если гость.
Нужно еще проверить верстку лендинга, посмотреть шобы он красиво смотрелся. Ну или хотя бы минимальный вариант разметки

**Comment by AlexeyShobanov** [comment]
Коля, ПР без комментариев остался. Что получилось - это не то?

**Comment by fey** [comment]
Я думал, Андрей верстку посмотрит.
Добавляй переводы.
