### ISSUE TITLE
Вернуть ссылку на топ пользователей для гостя

### ISSUE THREAD

**Issue by fey** [Hexlet/hexlet-sicp#459]
В данный момент ссылка на топ уехала в выпадающую менюшку, которая видна только для залогиневшегося пользователя.
Т.е. гостя она не видна. Надо вернуть или 
@AlexeyShobanov

**Comment by AlexeyShobanov** [comment]
Может быть рейтинг (кусочек на топ-5) вывести на велком под последними
комментариями и внизу добавить ссылку на полный рейтинг?
Просто вывести ссылку на рейтинг в навигации, мне кажется, как-то не логично
Если, ты считаешь, что так можно попробовать, могу добавить и посмотрим как
это выглядеть?
Это делать в рамках текущего ПР?

ср, 5 авг. 2020 г. в 11:33, Nikolay Gagarinov <notifications@github.com>:

**Comment by fey** [comment]
Нам пока надо лендинг прикрутить красивый, после него можно будет облагородить главную страницу, сделать типа дашборд со статистикой. Но рейтинг у нас спрятан и его фиг найдешь.

**Comment by AlexeyShobanov** [comment]
Вернул рейтинг в nav-bar

ср, 5 авг. 2020 г. в 14:13, Nikolay Gagarinov <notifications@github.com>:
