### ISSUE TITLE
Добавить в тексте упражнений ссылки на связанные упражнения

### ISSUE THREAD

**Issue by burenkov-anton** [Hexlet/hexlet-sicp#462]
В resources/views/exercise/listing/ в blade.php blade нужно сделать наподобие https://github.com/Hexlet/hexlet-sicp/pull/429/files#diff-d8d9950217fbf382c9422df86d267e79R1
В текстах упражнений поправить description, в ряде случаев преобразовать его в массив

**Comment by Malcom1986** [comment]
Добрый день.  Хочу  попробовать свои силы. Эта задача как раз подходящая, чтобы начать.  Как лучше поступить, чтобы не пересечься с другими участниками и не делать одни и те же упражнения?

**Comment by fey** [comment]
Привет. Посмотри в каких упражнениях можно добавить ссылки, если найдешь - напиши сюда, что добавишь ссылки

**Comment by Malcom1986** [comment]
Добавлю ссылки в упражнения 
1.24 и 1.26
