### ISSUE TITLE
СЕО: отсутствует h1

### ISSUE THREAD

**Issue by amshkv** [Hexlet/hexlet-sicp#479]
Отсутствует h1 на таких страницах, как:

* [x] https://sicp.hexlet.io/exercises
* [x] https://sicp.hexlet.io/ratings/top
* [x] https://sicp.hexlet.io/log (и далее)
* [x] https://sicp.hexlet.io/exercises/164 (и далее)

* [x] https://sicp.hexlet.io/ratings/progress_top
* [x] https://sicp.hexlet.io/ratings/comments_top
* [x] https://sicp.hexlet.io/password/reset
* [x] https://sicp.hexlet.io/ru/log

и тд

**Comment by dzencot** [comment]
Поправлю progress_top и comments_top

**Comment by artofwake** [comment]
Поправлю  /log

**Comment by artemvolt** [comment]
> Поправлю /log

Пока возвращаю обратно

**Comment by niyak93rus** [comment]
вроде по указанным ссылкам везде h1 есть. закроете issue?
