### ISSUE TITLE
СЕО: дублирующиеся h1

### ISSUE THREAD

**Issue by amshkv** [Hexlet/hexlet-sicp#481]
Дублируются h1 у пользователей, в части упражнений
https://sicp.hexlet.io/exercises/305
https://sicp.hexlet.io/exercises/353
https://sicp.hexlet.io/chapters
https://sicp.hexlet.io/users/1 (и далее)

**Comment by fey** [comment]
Можно поточнее? Вроде ничего нет :thinking:
