### ISSUE TITLE
Отсутствует единство именования упражнений

### ISSUE THREAD

**Issue by burenkov-anton** [Hexlet/hexlet-sicp#496]
![Имена упражнений](https://user-images.githubusercontent.com/11513918/90468955-d02dae80-e141-11ea-8385-2842c084c0f9.png)

**Comment by fey** [comment]
А можно побольше примеров? Пока не до конца понятно

**Comment by burenkov-anton** [comment]
По скриншоту выше:
В истории активности (https://sicp.hexlet.io/ru/log) при выполнении упражнения отображается его наименование, при добавлении решения - номер этого упражнения.

Плюс ещё:
На главной странице (https://sicp.hexlet.io/ru или https://sicp.hexlet.io/) в истории активности при выполнении упражнения указано что просто "выполнил упражнение", без названия или номера, при добавлении решения - указывается номер.
В моих решениях (https://sicp.hexlet.io/ru/my#nav-solutions) указывается и номер и название.
