### ISSUE TITLE
Некорректное склонение в лендинге

### ISSUE THREAD

**Issue by burenkov-anton** [Hexlet/hexlet-sicp#515]
![Склонение](https://user-images.githubusercontent.com/11513918/91385506-3f4e8580-e85b-11ea-8fb0-5a87babe3136.png)

**Comment by Malcom1986** [comment]
Возьму эту задачу

**Comment by fey** [comment]
Надо добавить плюрализм на перевод.

**Comment by Malcom1986** [comment]
Ага, добавил. Сейчас отправлю
