### ISSUE TITLE
Добавить в профиль ссылку на профиль пользователя на hexlet

### ISSUE THREAD

**Issue by fey** [Hexlet/hexlet-sicp#626]

**Comment by Malcom1986** [comment]
Попробую сделать

**Comment by fey** [comment]
@Malcom1986 как успехи?

**Comment by Malcom1986** [comment]
@fey нормально, начал делать, но пришлось отвлечься по семейным обстоятельствам. Доведу до конца чуть попозже

**Comment by fey** [comment]
@Michael57e подскажи, как проверял? на странице профиля выводится прфоиль Хекслета, если есть ник https://sicp.hexlet.io/users/4

**Comment by Michael57e** [comment]
вопрос снят
