### ISSUE TITLE
Обновиться на 5 бутстрап

### ISSUE THREAD

**Issue by fey** [Hexlet/hexlet-sicp#653]
Ниже указан список страниц (шаблонов), на которых нужно будет менять базовый шаблон на бс5 и собственно править верстку, если она поехала. Можно начать с малых страниц/наименее заметных.

* [x] #958
* [x] #1102
* [x] #1103
* [x] #1104
* [x] #1101
* [x] #1100
* [x] #1099
* [x] #1098
* [x] #1097
* [x] #960
* [x] #1096
* [x] #955
* [x] #953
* [x] #954
* [x] #951
* [x] #952
* [x] #956
* [x] #957
* [x] #950
* [x] #959

**Comment by Liocha** [comment]
Взял в работу.

**Comment by fey** [comment]
https://github.com/Hexlet/hexlet-sicp/issues/937

**Comment by ashikov** [comment]
@fey вроде все чекбоксы прочеканы. Нужно еще что-то проверить?

**Comment by fey** [comment]
ВРоде нет, можно закрывать.
