### ISSUE TITLE
Docker образ приложения для запуска

### ISSUE THREAD

**Issue by fey** [Hexlet/hexlet-sicp#657]
Необходимо сделать Образ приложения, который можно будет задеплоить на хероку или еще куда-то (пока на хероку).
Что там должно быть
1. Пыха 7.4+
2. nodeJS 14+
3. Docker, внутри докера нужно уметь запускать racket

В чем суть - чтобы запускать проверки необходимо уметь делать это безопасно. Например на Кодбазиксе это делается внутри докера. В Кодбатле тоже..
Таким образом приложение просто запустит процесс, посмотрит вывод и все. 
На данный момент приложение на хероку использует билдпаки и там не выходит грамотно заюзать racket, поэтому идея пока такая.

**Comment by tolyod** [comment]
займусь

**Comment by tolyod** [comment]
собрал нужные билдпаки [тут](https://github.com/tolyod/hexlet-sicp), по кнопке деплоиться в heroku, по окончании все бинарники racket-а ставятся в `~/.heroku/racket/bin/` и прописываются в $PATH

в обсуждении в [Slack](https://hexlet-ru.slack.com/archives/C0LN151B4/p1612962117102700?thread_ts=1611998568.083400&cid=C0LN151B4) решили  что для изоляции проще будет использовать [SandBox-ы](https://docs.racket-lang.org/reference/Sandboxed_Evaluation.html)

если такой вариант подходит делаю pull request?

**Comment by tolyod** [comment]
примерно так выглядит тест
```
#lang racket/base

(require racket/sandbox)

(define base-module-eval
  (make-module-evaluator '(module m racket/base
                            (require rackunit)
                            (require racket/unix-socket)
                            (require racket/tcp)
                            ;;; BEGIN
                            (define (sqr x) (* x x))

                            (define (average x y) (/ (+ x y) 2))

                            (define (improve guess x)
                              (average guess (/ x guess)))

                            (define (good-enough? guess x)
                              (< (abs (- guess x)) 0.0000001))

                            (define (sqrt-iter guess x)
                              (if (good-enough? guess (improve guess x))
                                  guess
                                  (sqrt-iter (improve guess x) x)))

                            (define (sqrt x)
                              (sqrt-iter 1.0 x))
                            ;;; END
                            (check-equal? (round (* 1000 (sqrt 4.0))) 2000.0)
                            (check-equal? (round (* 1000 (sqrt 100.0))) 10000.0)
                            (check-equal? (round (* 1000 (sqrt 1000000.0))) 1000000.0)
                            (check-equal? (round (* 1000 (sqrt 0.04))) 200.0)
                            (check-exn exn:fail? (lambda () (unix-socket-connect "/var/run/docker.sock")))
                            (check-exn exn:fail? (lambda () (tcp-connect "google.com" 443)))
                            )
                         )

  )
  ```

**Comment by fey** [comment]
Привет, да, сделай, пожалуйста, пулл реквест, посмотрим, что выходит.

**Comment by fey** [comment]
А для чего нужно
```
                            (require racket/unix-socket)
                            (require racket/tcp)
                            ```?

**Comment by tolyod** [comment]
> А для чего нужно
> 
> ```
>                             (require racket/unix-socket)
>                             (require racket/tcp)
>                             ```?
> ```

в Prod- не нужны, только для тестирования безопасности. 
Если их не добавить то последние 2 теста будут падать от того что нет нужных библиотек.
последние 2 теста пытаются постучаться в FS, затем в сесть, оба разу получают запрет.
