### ISSUE TITLE
Предлагаю добавить pre-wrap к страницам с решением

### ISSUE THREAD

**Issue by irkinwork** [Hexlet/hexlet-sicp#679]
Когда читаешь решения с объяснениями, приходится скроллить текст, не очень удобно.
![image](https://user-images.githubusercontent.com/34217652/107855036-264d8700-6e31-11eb-9175-d9e7ee3a262d.png)

Если добавить white-space: pre-wrap всё становится гораздо читаемее:

![image](https://user-images.githubusercontent.com/34217652/107855033-19c92e80-6e31-11eb-99db-5d53c649c7c6.png)

**Comment by fey** [comment]
@amshkv Можешь подсказать, как средствами бутстрапа можно пофиксить?

**Comment by amshkv** [comment]
средствами бутстрапа можно сделать вот так
https://getbootstrap.com/docs/4.6/utilities/text/#text-wrapping-and-overflow

но у меня вопросец, почему описание находится в `pre > code`, в котором как бы должен быть код, а не просто текст)

**Comment by fey** [comment]
Потому что есть упражнения, где мы пишем код и где мы пишем описание чего-то, например в каком порядке выполняется код.

**Comment by acidmaksim** [comment]
@fey Задача актуальна?

**Comment by fey** [comment]
да, тут надо править вывод

**Comment by Wenn911** [comment]
Взял в работу

**Comment by ashikov** [comment]
@Wenn911 есть результат?

**Comment by ashikov** [comment]
Исправлено в #1403
