### ISSUE TITLE
Улучшить листинги упражнений - добавить форматирование для примера-вывода

### ISSUE THREAD

**Issue by fey** [Hexlet/hexlet-sicp#689]
Пример - https://sicp.hexlet.io/ru/exercises/73
https://mitpress.mit.edu/sites/default/files/sicp/full-text/book/book-Z-H-15.html#%_thm_2.27

В оригинале результат процедуры обозначается курсивом.
Для улучшения юзабилити необходим добавить форматирование. чтобы этот вывод был отделен визуально от кода.

**Comment by vladimirkuvanovv** [comment]
взял в работу

**Comment by vladimirkuvanovv** [comment]
![изображение](https://user-images.githubusercontent.com/39465918/109546928-da127000-7adb-11eb-9f86-bc2b7f57b1ca.png)

до исправления
