### ISSUE TITLE
Add license

### ISSUE THREAD

**Issue by fey** [Hexlet/hexlet-sicp#707]
feycot:octocat:  22:37
В тему лицензий.
Нормально так? https://github.com/Hexlet/hexlet-sicp/pull/706/files
kirill.mokevnin  22:37
неа
22:37
смотрите у нас везде должна быть лицензия, что подобный код нельзя использовать у себя в закрытом виде
feycot:octocat:  22:38
А какую использовать?
kirill.mokevnin  22:38
просто представь что тут будет, любой может все это себе унести
22:38
и начать использовать как будто это их код
22:38
мы не для этого его открываем
22:38
подобное можно делать в общедоступных либах, которые мы для этого и делаем
22:38
но данный код он не для дарения другим, это просто открытость компании
22:38
и возможность участвовать остальным для прокачки
feycot:octocat:  22:39
Ох, где же ты был, когда я про лицензии спрашивал :sad_parrot:
kirill.mokevnin  22:40
но тут я тебе не отвечу
22:40
есть лицензия gpl
22:40
она допускает использование кода только в открытом по
22:40
но это не сосем то что нам надо, у нас же либа
22:40
есть ли спец лицензия на подобный конечный софт
22:40
который не является либой
22:40
что его нельзя брать себе и юзать
22:40
для заработка денег
feycot:octocat:  22:45
https://creativecommons.org/licenses/by-nc-sa/2.0/deed.ru вот тут некоммерческое использование
И обновленная https://creativecommons.org/licenses/by-nc-sa/4.0/ (edited) 
kirill.mokevnin  22:50
а есть более жесткая?
22:50
мы делаем контент
22:51
и не хотим чтобы например другие школы тупо брали и выкладывали их к себе на сайты
22:51
тоже самое касается сайта code-basics и других
22:51
то есть мы в принципе не подразумеваем что кто то взял эти сервисы и развернул у себя как часть сервиса
22:51
даже за бесплатно

**Comment by fey** [comment]
в качестве референса
https://github.com/aseprite/aseprite/blob/main/EULA.txt

**Comment by AABur** [comment]
@mokevnin вот несколько некоммерческих вариантов
https://directory.fsf.org/wiki/License:Commons-Clause
https://directory.fsf.org/wiki/License:UnivUtahRFPL
https://directory.fsf.org/wiki/License:SSSCFR-1.1

**Comment by acidmaksim** [comment]
@fey это еще актуально?

**Comment by fey** [comment]
Угу, надо придумать какую лицензию использовать, Какой лицензионый текст. Тпа несвободная но открытая.
