### ISSUE TITLE
Add SICP tests to CI

### ISSUE THREAD

**Issue by fey** [Hexlet/hexlet-sicp#721]

**Comment by acidmaksim** [comment]
@fey а можно подробнее? И насколько это актуально уже

**Comment by ashikov** [comment]
@fey Коля, а можешь тут чуть подробнее намекнуть на реализацию? В первом приближении получается, что нужно написать тест, который будет перебирать все файлы с решениями и запускать тесты для них для упражнений, где есть решения. Таким образом эта штука будет работать и локально, и в CI.

**Comment by fey** [comment]
да, примерно так и должно быть. Мы должны в CI прогонять тесты с нашими решениями.
