### ISSUE TITLE
Баги редактора

### ISSUE THREAD

**Issue by fey** [Hexlet/hexlet-sicp#730]
1. Косячный вывод
```
--------------------
FAILURE
name:       check-equal?
location:   program:?:?
actual:     1
expected:   13
--------------------
--------------------
FAILURE
name:       check-equal?
location:   program:?:?
actual:     4
expected:   25
--------------------
--------------------
FAILURE
name:       check-equal?
location:   program:?:?
actual:     1
expected:   2
--------------------
--------------------
FAILURE
name:       check-equal?
location:   program:?:?
actual:     2
expected:   13
--------------------
44cb730c420480a0477b505ae68af508fb90f96cf0ec54c6ad16949dd427f13a.rkt: raco test: non-empty stderr: #"--------------------\nFAILURE\nname:       check-equal?\nlocation:   program:?:?\nactual:     1\nexpected:   13\n--------------------\n--------------------\nFAILURE\nname:       check-equal?\nlocation:   program:?:?\nactual:     4\nexpected:   25\n--------------------\n--------------------\nFAILURE\nname:       check-equal?\nlocation:   program:?:?\nactual:     1\nexpected:   2\n--------------------\n--------------------\nFAILURE\nname:       check-equal?\nlocation:   program:?:?\nactual:     2\nexpected:   13\n--------------------\n"
```

2. При обновлении редактора пропадает подсветка кода во вкладке тестов.

**Comment by fey** [comment]
Ага, все так и есть.
Надо либо событие Livewire использовать и слушать их, чтобы ререндерить подсветку, либо запилить на каком-нибудь реакте :D

**Comment by tolyod** [comment]
такс, поднял локально, глянул, и обнаружил еще одну проблему (возможно), на каждое нажатие внутри редактора решения идёт запрос + ответ с/на сервер. Кажется это оверхед, зачем это тут? вроде как достаточно только на "запуск" решения реагировать?

**Comment by fey** [comment]
да, надо глянуть, Как это порешать. Я в livewire не очень разобрался(

**Comment by tolyod** [comment]
займусь

**Comment by tolyod** [comment]
@fey хочу немного поменять вывод лога тестов на такой:
![image](https://user-images.githubusercontent.com/1892972/111979998-c83e4e80-8b16-11eb-8765-8ef981e8eedc.png)
![image](https://user-images.githubusercontent.com/1892972/111980072-dc824b80-8b16-11eb-9a73-f588cfe8edef.png)

это схема vbnet в highlight.js, или оставить как есть?

**Comment by tolyod** [comment]
еще не понятно стоит ли убирать горизонтальную прокрутку вывода тестов?
сейчас так:
![image](https://user-images.githubusercontent.com/1892972/111983950-ccb93600-8b1b-11eb-8547-b54a83af3bb7.png)
можно сделать так:
![image](https://user-images.githubusercontent.com/1892972/111984004-e22e6000-8b1b-11eb-90ee-95692144487a.png)

**Comment by fey** [comment]
Мне кажется, что отсутствие горизонтального вывода непрозрачно, типа перенос строки и тд.
Может кто-то еще посмотрит и даст фидбек.
