### ISSUE TITLE
Make a React editor like code-basics

### ISSUE THREAD

**Issue by fey** [Hexlet/hexlet-sicp#854]
Сверстать и собрать редактор, заменить текущий на livewire. 
Если не хватает каких-то методов с бекенда - сделать заглушки. 
Использовать codemirrror для подсветки синтаксиса.

Тикетос - https://trello.com/c/iAIVp35l/17-%D1%81%D0%B4%D0%B5%D0%BB%D0%B0%D1%82%D1%8C-%D1%80%D0%B5%D0%B4%D0%B0%D0%BA%D1%82%D0%BE%D1%80-%D0%BD%D0%B0-react-%D0%BA%D0%B0%D0%BA-%D0%BD%D0%B0-code-basics
Фидбек https://github.com/Hexlet/hexlet-sicp/issues/887 

- [ ]  При попытке запустить решение всплывает окно подтверждения действия. После подтверждения ничего не происходит
- [ ]  На закладке editor шаблон кода вне зависимости от того нужно ли в задаче писать код решения или нет
- [x]  Вкладки editor, output, testForExercise не переведены
- [x]  Не видно самих тестов которые должны проверять упражнение
- [ ] Пропала кнопка "сохранить решение"

**Comment by alex-ismailov** [comment]
В работе.

**Comment by fey** [comment]
Добавил метод для получения инфы о текущем упражнении
https://sicp.hexlet.io/api/exercises/3

**Comment by acidmaksim** [comment]
@fey какая часть этого задания сделана? Вижу коммиты есть, но не один чекбокс не отмечен

**Comment by fey** [comment]
Часть отметил, но нужно пробежаться что еще осталось доделать.
