### ISSUE TITLE
Нечитабельное название выделенного раздела в упражнениях

### ISSUE THREAD

**Issue by burenkov-anton** [Hexlet/hexlet-sicp#884]
![lesson_ch_color](https://user-images.githubusercontent.com/11513918/120766142-212d5880-c544-11eb-8f5f-c1402a358af8.png)

**Comment by burenkov-anton** [comment]
В разделе прогресса аналогично

**Comment by fey** [comment]
такая же фигня на табах в ревью https://sicp.hexlet.io/ru/solutions/434#pills-434
