### ISSUE TITLE
Editor not working correctly

### ISSUE THREAD

**Issue by burenkov-anton** [Hexlet/hexlet-sicp#887]
![Редактор](https://user-images.githubusercontent.com/11513918/120879171-b0417b80-c5eb-11eb-955d-2cc362207306.png)

**Comment by burenkov-anton** [comment]
1. При попытке запустить решение всплывает окно подтверждения действия. После подтверждения ничего не происходит
2. На закладке editor шаблон кода вне зависимости от того нужно ли писать решение или нет
3. Вкладки editor, output, testForExercise не переведены
4. Не видно самих тестов которые должны проверять упражнение

**Comment by burenkov-anton** [comment]
Плюс пропала кнопка сохранить

**Comment by fey** [comment]
Ага, новый редактор в работе, забыли убрать wip изменения.
Новый редактор закомментировать 
@alex-ismailov фидбек по новому редактору (чего еще не хватает добавить)

**Comment by fey** [comment]
Кажется все это пофиксили
