### ISSUE TITLE
Не работает форматирование вывода в примерах

### ISSUE THREAD

**Issue by burenkov-anton** [Hexlet/hexlet-sicp#891]
![Форматирование](https://user-images.githubusercontent.com/11513918/120893034-3e911e00-c63b-11eb-9487-b936846eec0e.png)

#689

**Comment by fey** [comment]
Хм, но ведь работает
![image](https://user-images.githubusercontent.com/697178/120896374-a6933480-c63a-11eb-8961-fc227c1a506a.png)

**Comment by burenkov-anton** [comment]
@fey На твоём скриншоте нет вывода результата, только определение и вызов без вывода результата этого вызова.
Я имел ввиду, что была задача #689, где вывод результата процедуры был отображен курсивом.
 Сейчас разницы между определениями/ вызовами процедур и выводом результата процедур нет - курсив отсутствует.
 Если так и надо или цветовое выделение кода достаточно - то хорошо :)
